Repository cython/cython, pull requests merged in 2019-10, with the labels that each got.

#3186 FIX: do not include tp_print for py39
  Cython/Compiler/TypeSlots.py
Labels: Code Generation, defect

#3179 Add most non-modifying sequence operations to libcpp.algorithm
  Cython/Includes/libcpp/algorithm.pxd
  Cython/Includes/libcpp/iterator.pxd
  Cython/Includes/libcpp/string.pxd
  tests/run/cpp_stl_algo_nonmodifying_sequence_ops.pyx
Labels: C++, Library, enhancement

#3187 Fix --parallel support in build_ext.build_extensions()
  Cython/Distutils/old_build_ext.py
Labels: Build System, defect

#3183 Allow docstrings in c++ classes
  Cython/Compiler/Parsing.py
Labels: C++, enhancement

#3188 Add most modifying sequence operations to libcpp.algorithm
  Cython/Includes/libcpp/algorithm.pxd
  Cython/Includes/libcpp/string.pxd
  tests/run/cpp_stl_algo_modifying_sequence_ops.pyx
  tests/run/cpp_stl_algo_nonmodifying_sequence_ops.pyx
  tests/run/libcpp_algo.pyx
Labels: C++, Library, enhancement

#3196 Improve error presentation in IPython magic
  Cython/Build/IpythonMagic.py
Labels: Build System, Error Reporting
