Repository cython/cython, pull requests merged in 2019-07, with the labels that each got.

#3030 Fix error positions of undefined builtins and constants
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  tests/run/error_pos.srctree
Labels: Code Generation, Error Reporting, defect

#3032 Fix 32-bit build compat for Pythran
  Cython/Compiler/Pythran.py
Labels: Code Generation, Pythran

#3013 Describe refcount behaviour of object vs PyObject*
  docs/examples/userguide/language_basics/parameter_refcount.pyx
  docs/src/userguide/language_basics.rst
Labels: Documentation

#3017 runtests: keep also .i, .ii and .s files (generated by -save-temps)
  runtests.py
Labels: Testing

#3049 Return Py_ssize_t instead of size_t for len(memoryview).
  Cython/Compiler/Optimize.py
  Cython/Utility/StringTools.c
Labels: Buffers, Type Analysis, defect
