Repository cython/cython, pull requests merged in 2019-12, with the labels that each got.

#3115 ENH: add more tests and fixes for @property cdef decorator
  Cython/Compiler/ExprNodes.py
  tests/run/ext_attr_getter.srctree
Labels: Cython Language Feature, enhancement

#3280 Simplify the utility code loading
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Tests/TestUtilityLoad.py
Labels: Build System, enhancement

#3289 Fix temp variable handling for the super() class cell.
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  tests/run/py3k_super.pyx
Labels: Code Generation, defect
