Repository cython/cython, pull requests merged in 2019-03, with the labels that each got.

#2883 Support CPython builds with docstrings disabled
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/TypeSlots.py
Labels: Code Generation, enhancement

#2889 cythonize --no-docstrings
  Cython/Build/Cythonize.py
Labels: Build System, enhancement

#2893 include: posix.mman += mlock2, MLOCK_ONFAULT, MCL_ONFAULT
  Cython/Includes/posix/mman.pxd
Labels: Library, enhancement

#2894 include: posix.mman += MAP_FAILED
  Cython/Includes/posix/mman.pxd
Labels: Library, enhancement

#2900 Avoid generating a tp_new() function for extension types that do not need their own one.
  CHANGES.rst
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/TypeSlots.py
  tests/run/exttype.pyx
  tests/run/tp_new.pyx
Labels: Code Generation, Optimization

#2904 Remove Cython/Includes/Deprecated
  Cython/Compiler/Main.py
  Cython/Includes/Deprecated/python.pxd
  Cython/Includes/Deprecated/python_bool.pxd
  Cython/Includes/Deprecated/python_buffer.pxd
  Cython/Includes/Deprecated/python_bytes.pxd
  Cython/Includes/Deprecated/python_cobject.pxd
  Cython/Includes/Deprecated/python_complex.pxd
  Cython/Includes/Deprecated/python_dict.pxd
  Cython/Includes/Deprecated/python_exc.pxd
  Cython/Includes/Deprecated/python_float.pxd
  Cython/Includes/Deprecated/python_function.pxd
  Cython/Includes/Deprecated/python_getargs.pxd
  Cython/Includes/Deprecated/python_instance.pxd
  Cython/Includes/Deprecated/python_int.pxd
  Cython/Includes/Deprecated/python_iterator.pxd
  Cython/Includes/Deprecated/python_list.pxd
  Cython/Includes/Deprecated/python_long.pxd
  Cython/Includes/Deprecated/python_mapping.pxd
  Cython/Includes/Deprecated/python_mem.pxd
  Cython/Includes/Deprecated/python_method.pxd
  Cython/Includes/Deprecated/python_module.pxd
  Cython/Includes/Deprecated/python_number.pxd
  Cython/Includes/Deprecated/python_object.pxd
  Cython/Includes/Deprecated/python_oldbuffer.pxd
  Cython/Includes/Deprecated/python_pycapsule.pxd
  Cython/Includes/Deprecated/python_ref.pxd
  Cython/Includes/Deprecated/python_sequence.pxd
  Cython/Includes/Deprecated/python_set.pxd
  Cython/Includes/Deprecated/python_string.pxd
  Cython/Includes/Deprecated/python_tuple.pxd
  Cython/Includes/Deprecated/python_type.pxd
  Cython/Includes/Deprecated/python_unicode.pxd
  Cython/Includes/Deprecated/python_version.pxd
  Cython/Includes/Deprecated/python_weakref.pxd
  Cython/Includes/Deprecated/stdio.pxd
  Cython/Includes/Deprecated/stdlib.pxd
  Cython/Includes/Deprecated/stl.pxd
  setup.py
Labels: Build System, cleanup

#2896 fix bazel rule pyx_library example
  Tools/rules.bzl
Labels: Build System

#2909 Avoid generating empty tp_new() functions
  Cython/Compiler/TypeSlots.py
Labels: Code Generation, Optimization
