Repository cython/cython, pull requests merged in 2019-02, with the labels that each got.

#2839 Avoid GCC diagnostic pragma if GCC < 4.6
  Cython/Utility/TypeConversion.c
Labels: Code Generation, defect

#2842 @cython.trashcan directive to enable the Python trashcan for deallocations
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Options.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Utility/ExtensionTypes.c
  tests/run/trashcan.pyx
Labels: Code Generation, defect, feature

#2860 Allow condition in GILStatNode
  Cython/Compiler/Nodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.py
  docs/src/userguide/external_C_code.rst
  docs/src/userguide/fusedtypes.rst
  tests/errors/nogil_conditional.pyx
  tests/run/nogil_conditional.pyx
Labels: Cython Language Feature, feature
