Repository cython/cython, pull requests merged in 2019-08, with the labels that each got.

#3001 Argparse for cython
  Cython/Build/Cythonize.py
  Cython/Compiler/CmdLine.py
  Cython/Compiler/Tests/TestCmdLine.py
Labels: Build System, enhancement

#3082 Include memoryview C-API
  Cython/Includes/cpython/memoryview.pxd
  tests/run/cython_includes.pyx
Labels: Library, feature

#3070 [RFC] Fix for await inside f-string
  Cython/Compiler/Scanning.pxd
  Cython/Compiler/Scanning.py
  tests/run/fstring.pyx
Labels: Parsing, defect

#3086 Test that *args tuple is not copied if possible
  tests/run/extstarargs.pyx
  tests/run/starargs.pyx
Labels: Testing, enhancement

#3088 Fix coverage on trivial module (see #1985)
  Cython/Coverage.py
  tests/run/coverage_cmd_src_layout.srctree
Labels: Tools, defect

#3087 Refactor SliceTupleAndList utility code
  Cython/Utility/ObjectHandling.c
Labels: Code Generation, enhancement

#3081 Unicode identifiers (PEP 3131)
  Cython/Compiler/Code.py
  Cython/Compiler/Errors.py
  Cython/Compiler/Lexicon.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/StringEncoding.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/Visitor.py
  bin/cython-generate-lexicon.py
  tests/run/unicode_identifiers.pxd
  tests/run/unicode_identifiers.pyx
  tests/run/unicode_identifiers_import.pyx
Labels: Python Semantics, feature

#3100 __Pyx_GetNameInClass() should get raw attribute from __dict__
  Cython/Utility/ObjectHandling.c
  tests/run/cclass_assign_attr_GH3100.pyx
Labels: Code Generation, Python Semantics, defect

#3095 BUG: support wider use of @property decorator on CClassDef AttributeNodes
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Includes/numpy/__init__.pxd
  tests/run/ext_attr_getter.srctree
Labels: Cython Language Feature, feature

#3021 Use METH_FASTCALL on Python >= 3.7
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/TypeSlots.py
  Cython/Utility/FunctionArguments.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  tests/run/fastcall.pyx
  tests/run/str_subclass_kwargs.pyx
Labels: Code Generation, Optimization, feature

#3102 Special-case setting __new__ in class
  Cython/Compiler/ExprNodes.py
  Cython/Utility/ObjectHandling.c
  tests/run/set_new.py
Labels: Python Semantics, defect

#3104 Consistently name "closure" argument for Cython functions
  Cython/Utility/CythonFunction.c
Labels: cleanup

#3105 Rename self_result_code -> closure_result_code
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ParseTreeTransforms.py
Labels: cleanup

#3108 Utility/CppConvert: fix Cython warning
  Cython/Utility/CppConvert.pyx
Labels: Error Reporting, Type Analysis
