Repository cython/cython, pull requests merged in 2019-04, with the labels that each got.

#2931 Add PyGILState_Check to Includes/cpython/pystate.pxd
  Cython/Includes/cpython/pystate.pxd
Labels: Library, enhancement

#2930 Clean weakrefs before calling user's dealloc
  Cython/Compiler/ModuleNode.py
Labels: Code Generation, defect

#2935 GH-2934: improve error reporting for non-constant exception value expressions
  Cython/Compiler/Nodes.py
  tests/errors/nonconst_excval.pyx
Labels: Type Analysis, defect
