Repository cython/cython, pull requests merged in 2020-09, with the labels that each got.

#3795 Fixes `return None` in CodeWriter.
  Cython/CodeWriter.py
  Cython/Tests/TestCodeWriter.py
Labels: Code Generation, defect

#3803 Fix #2749 - Cython 0.29 broke support for C++ enum classes.
  Cython/Utility/TypeConversion.c
Labels: Code Generation, defect

#3811 Define extern `PyBUF_MAX_NDIM`
  Cython/Includes/cpython/buffer.pxd
Labels: Library, enhancement

#3810 Created a glossary and added one new entry
  docs/src/userguide/glossary.rst
  docs/src/userguide/index.rst
Labels: Documentation

#3228 Call destructors for structs in C++
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/TypeSlots.py
  tests/run/cpp_classes.pyx
Labels: C++, feature

#3812 Avoid parsing failure on cast to ctuple
  Cython/Compiler/Parsing.py
  tests/run/ctuple.pyx
Labels: Type Analysis, defect

#3813 Add doc support for cpdef enum
  Cython/Compiler/Nodes.py
  Cython/Compiler/Parsing.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Utility/CpdefEnums.pyx
  tests/run/cpdef_enums.pxd
  tests/run/cpdef_enums.pyx
  tests/run/cpdef_scoped_enums.pyx
Labels: Cython Language Feature, enhancement

#3836 Some more glossary entries
  docs/src/tutorial/cython_tutorial.rst
  docs/src/tutorial/memory_allocation.rst
  docs/src/tutorial/pure.rst
  docs/src/userguide/extension_types.rst
  docs/src/userguide/glossary.rst
  docs/src/userguide/language_basics.rst
  docs/src/userguide/parallelism.rst
  docs/src/userguide/wrapping_CPlusPlus.rst
Labels: Documentation

#3852 improvised Docs
  README.rst
Labels: Documentation
