Repository cython/cython, pull requests merged in 2020-07, with the labels that each got.

#3717 Validate and fix temp releasing (GH-3708)
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  tests/run/cpp_classes.pyx
Labels: defect

#3514 Fixes CodeWriter for `cdef` functions aka. CFuncDefNode.
  Cython/CodeWriter.py
  Cython/Tests/TestCodeWriter.py
Labels: Code Generation, enhancement

#3721 Avoid calling PyUnicode_FromUnicode() in Py3
  Cython/Utility/StringTools.c
Labels: Code Generation, defect

#3728 always consider 0-sized arrays as C- and F-contiguous
  Cython/Utility/MemoryView_C.c
  tests/memoryview/relaxed_strides.pyx
Labels: Buffers, defect

#3686 Additional unordered_map template defaults
  Cython/Includes/libcpp/unordered_map.pxd
  tests/run/cpp_stl_cpp11.pyx
  tests/run/cpp_unordered_map_helper.h
Labels: C++, Library, enhancement

#3667 Handle `for x in cpp_function_call()`
  Cython/Compiler/ExprNodes.py
  tests/run/cpp_iterators.pyx
Labels: C++, Code Generation, defect

#3746 Don't create CReference in C (only c++)
  Cython/Compiler/ExprNodes.py
Labels: Code Generation, defect

#3755 Fixed reference types being passed to getitemint
  Cython/Compiler/ExprNodes.py
  tests/run/lvalue_refs.pyx
Labels: C++, Code Generation, Type Analysis, defect
