Repository cython/cython, pull requests merged in 2020-01, with the labels that each got.

#3297 Remove legacy imports from IPython integration
  Cython/Build/IpythonMagic.py
  Cython/Build/Tests/TestIpythonMagic.py
Labels: Build System, defect

#3268 Fixed handling of kwds in generator closures
  Cython/Compiler/Nodes.py
  tests/run/generators.pyx
Labels: Code Generation, defect

#3273 Add a hook to change how `utilities` files are read.
  Cython/Compiler/Code.py
Labels: Build System, enhancement

#3223 Add LIMITED_API support and remove static state
  .travis.yml
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/TypeSlots.py
  Cython/Utility/Exceptions.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/ImportExport.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Optimize.c
  Cython/Utility/StringTools.c
  Cython/Utility/TypeConversion.c
  runtests.py
  tests/limited_api_bugs.txt
Labels: Code Generation, feature

#3241 Change goto label to avoid compile conflict
  Cython/Utility/ExtensionTypes.c
Labels: Code Generation, defect

#3236 #2740 emit_code_comments - removed from options, updated documentation
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Options.py
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#3312 Bugfix bitwise and with negative operand
  Cython/Utility/Optimize.c
  tests/run/pyintop.pyx
Labels: Code Generation, defect

#3307 Support Pythran shape
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Utility/CppSupport.cpp
  tests/run/numpy_pythran.pyx
Labels: Pythran, feature

#3271 FIX: Declare cimported ctuples (GH-1427)
  Cython/Compiler/ModuleNode.py
  tests/compile/ctuple_cimport.pxd
  tests/compile/ctuple_cimport_T1427.pyx
Labels: Code Generation, defect

#2891 provide support for the complex library
  Cython/Includes/libc/complex.pxd
  tests/run/complex_numbers_cmath_T2891.pyx
Labels: Library, feature

#3164 Fixed default buffer arguments with binding [Fixes `bufaccess`]
  Cython/Compiler/ExprNodes.py
  tests/buffers/bufaccess.pyx
Labels: Buffers, Testing, defect

#3340 Use the correct post-analysed bases, mkw and metaclass in Python class creation
  CHANGES.rst
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  tests/run/pyclass_dynamic_bases.pyx
Labels: Type Analysis, defect
