Repository cython/cython, pull requests merged in 2020-05, with the labels that each got.

#3562 Memoryviews of arrays of structs fix
  Cython/Utility/Buffer.c
  tests/buffers/buffmt.pyx
  tests/memoryview/numpy_memoryview.pyx
Labels: Buffers, Code Generation, defect

#3571 Rewrite the C property feature
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Pipeline.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Includes/numpy/__init__.pxd
  tests/run/ext_attr_getter.srctree
  tests/run/numpy_parallel.pyx
Labels: Cython Language Feature, enhancement

#3577 Support for versioned pxd files
  Cython/Compiler/Main.py
  Cython/Utils.py
  tests/run/versioned_pxds.srctree
Labels: Build System, enhancement

#3593 Reimplement __Pyx_PyDict_GetItemStrWithError() in Py2 to fix a refleak
  CHANGES.rst
  Cython/Utility/ModuleSetupCode.c
Labels: Code Generation, defect

#3589 Fix optimised string formatting for '%d'
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  tests/run/fstring.pyx
Labels: Code Generation, Optimization, defect

#3599 Fixed illegal casting of struct via ctuple
  Cython/Compiler/PyrexTypes.py
  tests/windows_bugs.txt
Labels: Code Generation, defect

#3608 Run ParallelRangeTransform on function arguments
  Cython/Compiler/ParseTreeTransforms.py
  tests/run/parallel.pyx
Labels: Type Analysis, defect

#3606 BUG: PyArray_SearchSorted signature
  Cython/Includes/numpy/__init__.pxd
  tests/run/numpy_test.pyx
Labels: Library, defect, numpy

#3615 Ensure utility code keeps the directives that it was compiled with
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Pipeline.py
  tests/memoryview/memoryview_no_binding_T3613.pyx
Labels: defect

#3591 Fix overflow_check
  Cython/Utility/Overflow.c
  tests/run/overflow_check.pxi
Labels: Code Generation, defect

#3619 Fixed "test_*_path_exists" + CompilerDirectivesNode
  Cython/Compiler/ParseTreeTransforms.py
  tests/compile/tree_assertions.pyx
Labels: Testing, defect

#3621 Use platform dependent test for unpacked_struct_with_arrays
  tests/buffers/buffmt.pyx
Labels: Testing, defect

#3630 ENH: port numpy #16266
  Cython/Includes/numpy/__init__.pxd
Labels: Library, numpy

#3605 Change default of "always_allow_keywords" directive to True
  CHANGES.rst
  Cython/Compiler/Nodes.py
  Cython/Compiler/Options.py
  Cython/Utility/FunctionArguments.c
  Cython/Utility/TestCythonScope.pyx
  docs/src/userguide/source_files_and_compilation.rst
  tests/buffers/bufaccess.pyx
  tests/compile/fused_redeclare_T3111.pyx
  tests/memoryview/memoryview.pyx
  tests/memoryview/memslice.pyx
  tests/run/always_allow_keywords_T295.pyx
  tests/run/cyfunction_METH_O_GH1728.pyx
  tests/run/exceptionrefcount.pyx
  tests/run/refcount_in_meth.pyx
  tests/run/unicode_identifiers.pyx
Labels: Python Semantics, defect

#3631 Initialization isn't required in sizeof or typeid
  Cython/Compiler/FlowControl.py
  tests/errors/w_uninitialized.pyx
  tests/errors/w_uninitialized_cpp.pyx
Labels: Error Reporting, defect

#3637 Ensure typeid is used only in C++ mode
  Cython/Compiler/ExprNodes.py
  tests/errors/e_cpp_only_features.pyx
Labels: Error Reporting, enhancement

#3634 Fix overflow handling for signed int abs
  Cython/Compiler/ExprNodes.py
  tests/run/builtin_abs.pyx
Labels: Code Generation, defect

#3635 Limited API and cleanup for #2056.
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ExtensionTypes.c
Labels: cleanup

#3650 Small changes to get `--cython-compile-all` working again
  Cython/Build/Dependencies.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/ParseTreeTransforms.py
Labels: defect
