Repository cython/cython, pull requests merged in 2020-06, with the labels that each got.

#3660 classmethod should fallback to always calling PyClassMethod_New
  Cython/Utility/CythonFunction.c
  tests/run/classmethod.pyx
Labels: Python Semantics, defect

#3654 Fix a bug where fused_to_specific was applied too widely
  Cython/Compiler/Nodes.py
  tests/run/fused_types.pyx
Labels: Type Analysis, defect

#3664 Check for exceptions also when @returns() is used, not only for "->" return type annotations
  Cython/Compiler/ParseTreeTransforms.py
Labels: Cython Language Feature, Pure Python Mode, Python Semantics

#3644 Change the default of c_api_binop_methods to False.
  Cython/Compiler/Options.py
  tests/run/unicode_formatting.pyx
Labels: Python Semantics, feature

#3683 Always bind Cython functions in py3
  Cython/Utility/CythonFunction.c
Labels: Python Semantics, defect

#3640 Add support for C++ scoped enums
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Parsing.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Utility/CpdefEnums.pyx
  docs/src/userguide/wrapping_CPlusPlus.rst
  tests/compile/cppenum.pyx
  tests/errors/cpp_enum_redeclare.pyx
  tests/errors/e_cenum_with_type.pyx
  tests/run/cpdef_scoped_enums.pyx
  tests/run/cpdef_scoped_enums_import.srctree
  tests/run/cpp_scoped_enums.pyx
Labels: C++, Cython Language Feature, feature

#3692 MNT: expose PyUnicode_GET_LENGTH
  Cython/Includes/cpython/unicode.pxd
Labels: Library, enhancement

#3693 Avoid using tp_name when CYTHON_COMPILING_IN_LIMITED
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/Buffer.c
  Cython/Utility/Builtins.c
  Cython/Utility/CConvert.pyx
  Cython/Utility/Coroutine.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/FunctionArguments.c
  Cython/Utility/ImportExport.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Optimize.c
  Cython/Utility/TypeConversion.c
Labels: Code Generation, enhancement

#3707 Keep reference to module dict around in limited mode
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Utility/Builtins.c
Labels: Code Generation, enhancement

#3708 Validate and fix temp releasing
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  runtests.py
  tests/run/cpp_classes.pyx
Labels: Code Generation, defect

#3713 Flow control and names in finally blocks
  Cython/Compiler/FlowControl.py
  tests/compile/tryfinally.pyx
Labels: defect

#3587 Documentation for version-tagged pxd files
  docs/src/userguide/sharing_declarations.rst
Labels: Documentation

#3617 Implement generic optimized loop iterator with indexing and type inference for memoryviews
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/Options.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/TypeInference.py
  Cython/Compiler/UtilNodes.py
  tests/memoryview/memoryview.pyx
  tests/memoryview/memslice.pyx
  tests/memoryview/numpy_memoryview.pyx
  tests/run/bytearray_iter.py
Labels: Optimization

#3697 Really only use PyUnicode_FromUnicode() when needed
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/StringEncoding.py
  Cython/Compiler/Tests/TestStringEncoding.py
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/StringTools.c
  tests/compile/buildenv.pyx
  tests/run/unicodeliterals.pyx
Labels: Code Generation, defect
