Repository cython/cython, pull requests merged in 2020-03, with the labels that each got.

#3391 Fused arguments specified by annotation or locals
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  tests/run/pure_fused.pxd
  tests/run/pure_fused.py
Labels: Type Analysis, defect

#3398 Fixed crash with default arguments and bound fused functions
  Cython/Utility/CythonFunction.c
  tests/run/fused_def.pyx
Labels: Code Generation, Cython Language Feature, defect

#3386 Fixed issue where fused functions didn't register as cyfunctions
  Cython/Utility/CythonFunction.c
  tests/run/fused_def.pyx
Labels: Code Generation, Cython Language Feature, defect

#3379 Fixed initialization of cachedcfunction
  Cython/Compiler/Code.py
Labels: Code Generation, defect

#3257 fix indentation on annotation_typing docs
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#3421 Add missing declarations to number.pxd
  Cython/Includes/cpython/number.pxd
Labels: Documentation

#3429 Fix the cdiv() and cmod() definitions in Shadow.py
  Cython/Shadow.py
  tests/run/cdivision_CEP_516.pyx
Labels: Pure Python Mode, defect

#3437 Backports
  Cython/Utility/Exceptions.c
  Cython/Utility/ModuleSetupCode.c
Labels: Code Generation, defect

#3445 Add missing declarations to object.pxd
  Cython/Includes/cpython/object.pxd
Labels: Library

#3308 Pythran update: __builtin__ -> builtins
  Cython/Compiler/Pythran.py
Labels: Pythran

#3422 Updated documentation of multiple inheritence rules
  docs/src/userguide/extension_types.rst
Labels: Documentation

#3411 Add missing declarations to slice.pxd
  Cython/Includes/cpython/slice.pxd
Labels: Library, enhancement

#3409 BLD: update the trove classifier to include python 3.8
  setup.py
Labels: Documentation

#3402 Add genobject.pxd
  Cython/Includes/cpython/genobject.pxd
  tests/run/cython_includes.pyx
Labels: Library, enhancement

#3387 Add fpclassify() and FP_* constants to math.pxd
  Cython/Includes/libc/math.pxd
Labels: Library

#3441 Slight adjustment to documentation of "quiet" parameter for `cythonize()`.
  Cython/Build/Dependencies.py
Labels: Documentation

#3413 Marks view.* extension types as imported
  Cython/Compiler/CythonScope.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/PyrexTypes.py
  tests/memoryview/cythonarray.pyx
Labels: Cython Language Feature, enhancement

#3428 Mark missing argument errors as unlikely
  Cython/Compiler/Nodes.py
Labels: Code Generation, enhancement

#3244 __init__() call from cython.declare and cython.cast in Shadow.py
  Cython/Shadow.py
  tests/run/pure_py.py
Labels: Pure Python Mode, defect

#3465 Fixed initialization of the array with the list which was broken in GH-3244
  Cython/Shadow.py
  tests/run/pure_py.py
Labels: Pure Python Mode, defect

#3461 Use PEP 518 indication for Cython build-time dependency.
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#3468 Add marshal.pxd
  Cython/Includes/cpython/marshal.pxd
  tests/run/cython_includes.pyx
Labels: Library

#3440 Make `Shadow.inline()` caching account for language version and compilation environment.
  Cython/Build/Inline.py
  Cython/Build/Tests/TestInline.py
Labels: Build System, defect

#3463 Specialize fused function local variables specified with pure-python
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  tests/run/pure_fused.pxd
  tests/run/pure_fused.py
Labels: Pure Python Mode, defect

#3469 Cython header file for C++ `std::atomic` type
  Cython/Includes/libcpp/atomic.pxd
  tests/run/cpp_stl_atomic.pyx
  tests/run/libcpp_all.pyx
Labels: C++, Library, enhancement
