Repository cython/cython, pull requests merged in 2020-02, with the labels that each got.

#3341 bufaccess ref-counting tests and extstarargs test
  tests/buffers/bufaccess.pyx
  tests/run/extstarargs.pyx
Labels: Testing, defect

#3353 w_undeclared fix
  Cython/Compiler/ParseTreeTransforms.py
Labels: Cython Language Feature, Type Analysis, defect

#3351 Changed always_allow_keywords_T295 for Py3.9
  tests/run/always_allow_keywords_T295.pyx
Labels: Testing

#3348 Fixing declaration of inner OpenMP privates
  Cython/Compiler/Nodes.py
  tests/run/sequential_parallel.pyx
Labels: Code Generation, Cython Language Feature, defect

#3361 Fixed a bug with C++ comparison operators
  Cython/Compiler/ExprNodes.py
  tests/run/cpp_operator_exc_handling.pyx
  tests/run/cpp_operator_exc_handling_helper.hpp
Labels: C++, Code Generation

#3365 Redo numpy.pxd changes and update tests
  Cython/Includes/numpy/__init__.pxd
  docs/examples/tutorial/numpy/convolve2.pyx
  runtests.py
  tests/run/numpy_bufacc_T155.pyx
  tests/run/numpy_cimport.pyx
  tests/run/numpy_common.pxi
  tests/run/numpy_parallel.pyx
  tests/run/numpy_subarray.pyx
  tests/run/numpy_test.pyx
Labels: Library

#3375 Allow tempita includes to be more readily @required
  Cython/Compiler/Code.py
  Cython/Utility/ObjectHandling.c
Labels: Code Generation, enhancement

#3382 Fix the signature of _Py_PyAtExit()
  Cython/Includes/cpython/pylifecycle.pxd
Labels: Library, defect
