Repository cython/cython, pull requests merged in 2020-08, with the labels that each got.

#3762 Use a generic shape accessor for pythranized array
  Cython/Utility/CppSupport.cpp
Labels: Code Generation, Pythran, defect

#3782 Fix Python 3.4 + MSVC issue with elaborated type specifier for enum
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Utility/CppSupport.cpp
Labels: Code Generation, defect

#3542 Fixing cygdb
  Cython/Compiler/Annotate.py
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Debugger/Tests/codefile
  Cython/Debugger/Tests/test_libcython_in_gdb.py
  Cython/Debugger/libcython.py
  Cython/Debugger/libpython.py
  Cython/StringIOTree.py
  docs/src/userguide/debugging.rst
Labels: Debugger, defect

#3799 Improved documentation for annotation typing
  docs/src/tutorial/pure.rst
Labels: Documentation
