Repository cython/cython, pull requests merged in 2020-11, with the labels that each got.

#3894 Add O_DIRECT to posix/fcntl.pxd
  Cython/Includes/posix/fcntl.pxd
Labels: Library, enhancement

#3886 [RFC] Fix const in nested template arg
  Cython/Compiler/Parsing.py
  tests/compile/cpp_templates_nested.pyx
Labels: C++, Parsing, defect

#3899 Add codecs.pxd
  Cython/Includes/cpython/codecs.pxd
  tests/run/cython_includes.pyx
Labels: Library, enhancement

#3901 Add cellobject.pxd
  Cython/Includes/cpython/cellobject.pxd
  tests/run/cython_includes.pyx
Labels: Library, enhancement

#3893 Fix "common_include_dir" test on OS X on Travis
  .travis.yml
  tests/build/common_include_dir.srctree
Labels: Testing, defect

#3825 Port numpy#17150 __init__.pxd edits
  Cython/Includes/numpy/__init__.pxd
Labels: Library, enhancement, numpy

#3737 ENH: cproperties for datetime objects
  Cython/Includes/cpython/datetime.pxd
  tests/run/datetime_pxd.pyx
Labels: Library, enhancement

#3874 Fix memoryview self-assignment crash
  Cython/Compiler/FusedNode.py
  Cython/Compiler/MemoryView.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/MemoryView.pyx
  Cython/Utility/MemoryView_C.c
  tests/memoryview/memoryview.pyx
Labels: Code Generation, defect

#3833 Add small pointer guide in 'Interfacing with External C Code' chapter
  docs/src/userguide/external_C_code.rst
Labels: Documentation

#3902 Fix an error in CHANGES.rst
  CHANGES.rst
Labels: Documentation

#3905 Support namespace packages inside regular packages
  Cython/Utils.py
  tests/build/cythonize_pep420_namespace.srctree
Labels: Python Semantics, defect

#3921 [0.29] Fix usage of undefined C-API "_PyGen_Send" in Py3.10 with "PyIter_Send".
  Cython/Utility/Coroutine.c
Labels: Code Generation, defect
