Repository cython/cython, pull requests merged in 2020-10, with the labels that each got.

#3853 Fixed assorted crashes with fused types
  Cython/Compiler/Errors.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  tests/errors/fused_types.pyx
Labels: Error Reporting, enhancement

#3859 Error handling, further clarification/language
  docs/src/userguide/language_basics.rst
Labels: Documentation

#3864 Replaced Element.getiterator() with Element.iter().
  Cython/Compiler/ModuleNode.py
Labels: cleanup

#3865 Preferred Element.iter() to Element.getiterator().
  Cython/Compiler/ModuleNode.py
Labels: Build System, defect

#3870 Fix unused variable warnings resulting from disabling assertions
  Cython/Utility/MemoryView.pyx
Labels: Code Generation, defect

#3847 Removed `same_as` from Plex.Actions.Action
  Cython/Plex/Actions.pxd
  Cython/Plex/Actions.py
Labels: cleanup

#3850 Fix crash relating to annotated attributes
  Cython/Compiler/ExprNodes.py
  tests/run/annotation_typing.pyx
  tests/run/pep526_variable_annotations.py
Labels: Error Reporting, enhancement

#3858 Improve error reporting when users mistakenly write "&&" or "||" instead of Python's "and" and "or" operators.
  Cython/Compiler/Lexicon.py
  Cython/Compiler/Parsing.pxd
  Cython/Compiler/Parsing.py
  tests/errors/e_binop_and.pyx
  tests/errors/e_binop_or.pyx
Labels: Error Reporting, enhancement

#3884 Simplify the output stream capturing for the C compiler runs by using a temp file instead of threads.
  Cython/Utils.py
Labels: Testing, enhancement

#3882 Fix memoryview casts involving fused types
  Cython/Compiler/Nodes.py
  tests/run/fused_types.pyx
Labels: Type Analysis, defect
