Repository cython/cython, pull requests merged in 2021-03, with the labels that each got.

#4042 Port test_exceptions to Python 3.10
  tests/run/test_exceptions.pyx
Labels: Testing, defect

#4055 PyImport_GetModule unsupported in PyPy
  Cython/Utility/ImportExport.c
Labels: Code Generation, PyPy, defect

#4059 always return int from __Pyx_PyUnicode_KIND
  Cython/Utility/ModuleSetupCode.c
Labels: Code Generation, defect

#4039 Allow using nested types of typedefs
  Cython/Compiler/Nodes.py
  tests/run/cpp_nested_classes.pyx
Labels: C++, Type Analysis, defect

#4031 Temporarily pin Pythran version
  .travis.yml
Labels: Pythran

#4067 docs: use https links
  CHANGES.rst
  README.rst
  docs/examples/Cython Magics.ipynb
  docs/make.bat
  docs/src/quickstart/overview.rst
  docs/src/tutorial/appendix.rst
  docs/src/tutorial/clibraries.rst
  docs/src/tutorial/readings.rst
  docs/src/userguide/numpy_tutorial.rst
Labels: Documentation, enhancement

#4045 Make load_dynamic() compatible with Python 3.10
  Cython/Build/Inline.py
Labels: Build System, defect

#4049 Don't test for frozenset singleton on Python 3.10
  Cython/Utility/Builtins.c
  tests/run/set.pyx
Labels: Python Semantics, defect

#4044 Port test_asyncgen to Python 3.10
  tests/run/test_asyncgen.py
Labels: Testing, defect

#4051 Fixed CyFunction __self__ attribute
  Cython/Utility/CythonFunction.c
  tests/run/function_self.py
Labels: Python Semantics, defect

#4054 fix type conversions in vectorcallfunc
  Cython/Utility/CythonFunction.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
Labels: Code Generation, defect
