Repository cython/cython, pull requests merged in 2021-12, with the labels that each got.

#4473 Add tp_inline_values_offset to slot_table (0.29.x)
  Cython/Compiler/TypeSlots.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
Labels: defect, Code Generation

#4488 pyston support: backport memory corruption fix #4200 to v0.29 branch
  Cython/Utility/ExtensionTypes.c
Labels: defect, Code Generation

#4472 Add tp_inline_values_offset to slot_table
  Cython/Compiler/TypeSlots.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
Labels: defect, Code Generation

#4486 Remove pypy bugs tests
  .github/workflows/ci.yml
Labels: cleanup, Testing

#4358 Support cpp_locals and std::move on prange temps
  Cython/Compiler/Nodes.py
  tests/run/cpp_locals_parallel.pyx
Labels: C++, enhancement, Code Generation

#4337 Ban templating C++ classes with reference counted types
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  tests/errors/cpp_object_template.pyx
Labels: enhancement, Error Reporting, Type Analysis

#4130 Disabled embed test from the docs on Py3.4
  runtests.py
Labels: defect, Testing

#2813 [DOC] Add doc for memory views with custom numpy dtype
  docs/examples/userguide/memoryviews/custom_dtype.pyx
  docs/src/userguide/memoryviews.rst
Labels: Documentation

#4086 PyMem_(Raw)Calloc in CPython.mem
  Cython/Includes/cpython/mem.pxd
  Cython/Utility/ModuleSetupCode.c
  runtests.py
  tests/run/cpython_capi.pyx
  tests/run/cpython_capi_py35.pyx
Labels: enhancement, Library

#4311 Docs: Migrate profiling tutorial to pure python
  docs/examples/tutorial/profiling_tutorial/calc_pi.py
  docs/examples/tutorial/profiling_tutorial/calc_pi_2.py
  docs/examples/tutorial/profiling_tutorial/calc_pi_2.pyx
  docs/examples/tutorial/profiling_tutorial/calc_pi_3.py
  docs/examples/tutorial/profiling_tutorial/calc_pi_3.pyx
  docs/examples/tutorial/profiling_tutorial/calc_pi_4.py
  docs/examples/tutorial/profiling_tutorial/calc_pi_4.pyx
  docs/examples/tutorial/profiling_tutorial/often_called.py
  docs/examples/tutorial/profiling_tutorial/profile.py
  docs/examples/tutorial/profiling_tutorial/profile_2.py
  docs/src/tutorial/profiling_tutorial.rst
Labels: Documentation

#4121 Warn when cyfunction.__[kw]defaults__ is changed
  Cython/Utility/CythonFunction.c
  tests/run/cyfunction_defaults.pyx
Labels: enhancement, Error Reporting

#4339 Use cythonize in pyximport
  Cython/Build/Dependencies.py
  Cython/Distutils/build_ext.py
  pyximport/pyxbuild.py
  pyximport/pyximport.py
  tests/pyximport/pyximport_pyimport_only.srctree
  tests/pyximport/pyximport_pyxbld.srctree
Labels: feature, Build System

#4433 Don't error when exception_check is set to True when return type is PyObject.
  Cython/Compiler/Nodes.py
  tests/errors/pure_errors.py
  tests/run/pure_py3.py
Labels: defect, Type Analysis

#4494 Bugfix/pep448 in op unpack fix
  Cython/Compiler/Optimize.py
  tests/run/pep448_extended_unpacking.pyx
Labels: defect, Optimization

#4328 Changes needed to begin testing GraalPython
  Cython/Utility/ModuleSetupCode.c
  runtests.py
  tests/build/common_include_dir.srctree
  tests/graal_bugs.txt
Labels: enhancement, Code Generation

#3294 Add std::optional for c++17 (GH-3293)
  Cython/Includes/libcpp/optional.pxd
  tests/run/cpp_stl_optional.pyx
Labels: C++, feature, Library

#4392 Add partial circular import fix (and test) for #4390
  Cython/Utility/ImportExport.c
  tests/pypy2_bugs.txt
  tests/run/partial_circular_import.srctree
Labels: defect, Python Semantics

#4318 Allow releasing gil in nogil functions
  Cython/Compiler/Code.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Utility/ModuleSetupCode.c
  tests/run/nogil.pyx
Labels: defect, Code Generation

#3987 Remove ban on assignment to reference
  Cython/Compiler/ExprNodes.py
  tests/run/lvalue_refs.pyx
Labels: C++, defect, Type Analysis

#4498 Added options from old_build_ext to new_build_ext
  Cython/Distutils/build_ext.py
  docs/src/userguide/source_files_and_compilation.rst
  pyximport/pyxbuild.py
  setup.py
  tests/build/build_ext_cython_c_in_temp.srctree
  tests/build/build_ext_cython_cplus.srctree
  tests/build/build_ext_cython_include_dirs.srctree
Labels: enhancement, Build System

#4507 Use thread-local storage for the global error state
  Cython/Compiler/Builtin.py
  Cython/Compiler/Errors.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/Main.py
  Cython/Compiler/Pipeline.py
  Cython/Compiler/Symtab.py
  Cython/TestUtils.py
  tests/run/test_fstring.pyx
Labels: defect, Error Reporting

#4510 pin setuptools<60
  .github/workflows/wheel-manylinux.yml
  Tools/ci-run.sh
Labels: Testing

#4509 qualify use of tp_pypy_flags and tp_vectorcall on PyPy
  Cython/Compiler/TypeSlots.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
Labels: defect, Code Generation, PyPy

#4515 Fix class pointer annotations
  Cython/Compiler/ParseTreeTransforms.py
  tests/run/annotation_typing.pyx
Labels: defect, Type Analysis

#4517 Redo pypy tp flags
  Cython/Compiler/TypeSlots.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  tests/build/module_api.srctree
  tests/run/posonly.py
  tests/run/test_genericclass.py
  tests/run/test_genericclass_exttype.pyx
Labels: defect, Code Generation, PyPy

#4315 Allow default value for memory view
  Cython/Compiler/ExprNodes.py
  tests/run/cyfunction_defaults.pyx
Labels: defect, Type Analysis

#4527 add emplace_back to vector
  Cython/Includes/libcpp/vector.pxd
Labels: C++, enhancement, Library

#4523 Avoid double redirect in old documentation
  docs/src/reference/directives.rst
Labels: Documentation

#4526 Add `uio.pxd` and update some posix pxds
  Cython/Includes/posix/fcntl.pxd
  Cython/Includes/posix/mman.pxd
  Cython/Includes/posix/resource.pxd
  Cython/Includes/posix/select.pxd
  Cython/Includes/posix/stat.pxd
  Cython/Includes/posix/uio.pxd
  Cython/Includes/posix/wait.pxd
  Tools/gen_tests_for_posix_pxds.py
  tests/compile/posix_pxds.pyx
Labels: enhancement, Library

#4531 fix incorrect template definition
  Cython/Includes/libcpp/deque.pxd
  Cython/Includes/libcpp/vector.pxd
Labels: C++, defect, cleanup, Library

#4538 Remove python 2.5 mention from special_methods.rst
  docs/src/userguide/special_methods.rst
Labels: cleanup, Documentation
