Repository cython/cython, pull requests merged in 2021-08, with the labels that each got.

#4317 Suppress warnings about constant expressions on MSVC
  Cython/Compiler/Code.py
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation

#4323 Restore error on cdef function arbitrary decorator
  Cython/Compiler/ParseTreeTransforms.py
  tests/errors/cdef_func_decorators.pyx
Labels: defect, Error Reporting

#4333 Fixed internal link in the docs
  docs/src/userguide/special_methods.rst
Labels: Documentation

#4331 Fix bugs with Windows
  Cython/Compiler/Buffer.py
  Cython/TestUtils.py
Labels: defect, Code Generation

#4344 PyUnicode_CompareWithASCIIString fix signature
  Cython/Includes/cpython/unicode.pxd
Labels: defect, Library

#4353 Fix deduplication of tuples constaining IdentifierStringNode
  Cython/Compiler/ExprNodes.py
  tests/run/tuple_constants.pyx
Labels: enhancement, Code Generation

#4345 Update docs to recommend using MSVC on Windows
  docs/src/quickstart/install.rst
Labels: Documentation
