Repository cython/cython, pull requests merged in 2021-05, with the labels that each got.

#3953 docs: fix simple typo, equalivalent -> equivalent
  Cython/Utility/ModuleSetupCode.c
Labels: cleanup

#3932 Use Py_TYPE() and Py_REFCNT() macros
  Cython/Utility/Builtins.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/ObjectHandling.c
Labels: cleanup

#3815 Don't use symbolic links on Windows, it requires admin account.
  runtests.py
Labels: Testing, defect

#4144 Fixes #4143: Can't catch ValueError from float() calls
  Cython/Utility/TypeConversion.c
  tests/run/builtin_float.py
Labels: Code Generation, defect

#4081 Reduce memory allocations in C++ to PyList Conversions
  Cython/Utility/CppConvert.pyx
Labels: C++, Code Generation, enhancement

#4147 fix variable shadowing
  Cython/Utility/ExtensionTypes.c
Labels: Code Generation, defect

#4162 silence unused warnings in universal way
  Cython/Utility/AsyncGen.c
  Cython/Utility/Buffer.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/Exceptions.c
  Cython/Utility/ImportExport.c
  Cython/Utility/MemoryView_C.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Optimize.c
  Cython/Utility/StringTools.c
Labels: Code Generation, defect

#4151 Fix annotations for decorated classes
  Cython/Compiler/Nodes.py
  runtests.py
  tests/run/pep557_dataclasses.py
  tests/run/pep563_annotations.py
Labels: Python Semantics, defect

#4154 Use std::move in c++ during yield context switch.
  Cython/Compiler/ExprNodes.py
  runtests.py
  tests/compile/cpp_temp_assignment.pyx
Labels: C++, Code Generation, defect

#4178 Refuse to overwrite output files that probably were not created by Cython
  Cython/Compiler/ModuleNode.py
  Cython/Coverage.py
  Cython/Utils.py
  tests/run/existing_output_files.srctree
Labels: Error Reporting, enhancement

#4190 Support cimports in pure Python code.
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Shadow.py
  docs/src/tutorial/pure.rst
  tests/errors/e_pure_cimports.pyx
  tests/run/pure_py_cimports.py
  tests/run/pure_pyx_cimports.pyx
Labels: Pure Python Mode, feature

#4191 fix move on msvc
  Cython/Includes/libcpp/utility.pxd
Labels: Code Generation, enhancement

#4185 [ENH] Add operator= to shared_ptr for assignments to base classes
  Cython/Includes/libcpp/memory.pxd
  tests/run/cpp_smart_ptr.pyx
Labels: C++, Library, enhancement

#3611 Split the current "CYTHON_COMPILING_IN_LIMITED_API" macro guard
  .github/workflows/ci.yml
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/TypeSlots.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/CommonStructures.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/ImportExport.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Tools/ci-run.sh
  appveyor.yml
  tests/compile/types_and_names.pyx
  tests/limited_api_bugs.txt
  tests/run/cdef_multiple_inheritance_errors.srctree
  tests/run/pstats_profile_test.pyx
  tests/run/special_methods_T561.pyx
Labels: Code Generation, feature

#3626 Implement total_ordering
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Options.py
  Cython/Shadow.py
  tests/errors/e_exttype_total_ordering.pyx
  tests/run/exttype_total_ordering.pyx
Labels: Cython Language Feature, feature
