Repository cython/cython, pull requests merged in 2021-11, with the labels that each got.

#4403 Add "import_array()" to the Numpy tutorial
  docs/examples/tutorial/numpy/convolve2.pyx
Labels: Documentation

#4439 Fix GCC -Wsign-conversion warning
  Cython/Utility/ImportExport.c
Labels: Code Generation, P: trivial

#4423 Add most of the C++17 numeric functions to libcpp.numeric
  Cython/Includes/libcpp/numeric.pxd
  tests/run/cpp_stl_numeric_ops_cpp17.pyx
Labels: C++, enhancement, Library

#4454 use PyContextVar_Get backport until PyPy 7.3.6
  Cython/Includes/cpython/contextvars.pxd
Labels: enhancement, Code Generation, PyPy

#4435 removed a default mutable argument pitfall
  runtests.py
Labels: enhancement, Testing

#4440 Avoid coverage.py balking on "stringsource"
  Cython/Compiler/Scanning.py
  tests/run/coverage_cmd.srctree
Labels: defect, Pure Python Mode, Coverage

#4458 Remove unreachable code in Utility
  Cython/Utility/ObjectHandling.c
Labels: Code Generation, cleanup

#4427 Fix co-routine frames on Python 3.11 alpha
  Cython/Utility/Coroutine.c
Labels: enhancement, Code Generation

#4460 [cython-mode.el] Attempt to fix #3218 and other bugs around it
  Tools/cython-mode.el
Labels: defect, Tools

#4464 DOC Add a Performance section for Typed Memoryviews
  docs/src/userguide/memoryviews.rst
Labels: Documentation

#4468 Add Python 3.10 classifier (0.29.x backport)
  setup.py
Labels: Documentation

#4465 Get 0.29.x working on Python 3.11
  Cython/Utility/Coroutine.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
Labels: defect, Code Generation

#4462 Add merge and set operations of the C++ algorithm library
  Cython/Includes/libcpp/algorithm.pxd
  tests/macos_cpp_bugs.txt
  tests/run/cpp_stl_algo_sorted_ranges_other_ops.pyx
  tests/run/cpp_stl_algo_sorted_ranges_set_ops.pyx
Labels: C++, enhancement, Library

#4453 Only set HAVE_VECTORCALL flag when using vectorcall
  Cython/Compiler/ModuleNode.py
  Cython/Utility/CythonFunction.c
Labels: defect, Code Generation

#4478 PYPY: pypy does not implement PyCode_NewWithPosOnlyArgs
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation, PyPy

#4475 Disable Cython reimplementation of trashcan
  Cython/Utility/ExtensionTypes.c
Labels: Code Generation, cleanup

#4474 Fixed uninitialized test on 3.11
  tests/run/uninitialized.py
Labels: defect, Testing

#4480 Disable USE_UNICODE_WRITER for limited api and Py3.11
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation

#4479 Exceptions.c PyCode_New -> PyCode_NewEmpty
  Cython/Utility/Exceptions.c
Labels: Code Generation, cleanup

#4477 PYPY: do not call __Pyx_Coroutine_del (tp_finalize) - it reconstructs dead objects
  Cython/Utility/Coroutine.c
  tests/pypy_bugs.txt
  tests/pypy_crash_bugs.txt
Labels: defect, Code Generation, PyPy

#4471 Disable pycontextvar test on PyPy
  tests/pypy_bugs.txt
  tests/pypy_crash_bugs.txt
  tests/run/pycontextvar.pyx
Labels: defect, Testing, PyPy

#4482 Remove warning from unused temp in module init
  Cython/Compiler/ModuleNode.py
Labels: defect, Code Generation

#4485 Recategorize a few pypy bugs, fix some others
  tests/pypy2_bugs.txt
  tests/pypy_bugs.txt
  tests/pypy_implementation_detail_bugs.txt
  tests/run/matrix_multiplier.pyx
  tests/run/test_genericclass.py
  tests/run/test_genericclass_exttype.pyx
  tests/run/unicodemethods.pyx
Labels: enhancement, Testing, PyPy
