Repository cython/cython, pull requests merged in 2021-06, with the labels that each got.

#4203 Fix compile error preventing building in MSVC
  Cython/Utility/CythonFunction.c
Labels: Code Generation, defect

#4210 change extension for sphinx 1.8+
  docs/conf.py
Labels: Documentation, defect

#4211 remove special handling of Pyston
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/Profile.c
  tests/compile/buildenv.pyx
Labels: Code Generation, cleanup

#4216 Backport #2811 to fix qualified-name issues
  Cython/Compiler/Symtab.py
  tests/run/cython3.pyx
Labels: Type Analysis, defect

#4219 Changed test for GH4212
  tests/run/cpp_classes_def.pyx
Labels: Testing, enhancement

#4236 tweak 1027db04 for older versions of PyPy
  Cython/Utility/Builtins.c
Labels: Code Generation, PyPy, defect

#4233 Optimise "[...] * N" where N is a non-literal C integer value.
  Cython/Compiler/ExprNodes.py
  tests/run/seq_mul.py
Labels: Optimization, enhancement

#4231 Fixed conversion from DictNode to map
  Cython/Compiler/ExprNodes.py
  tests/errors/reversed_literal_pyobjs.pyx
  tests/run/cpp_stl_conversion.pyx
Labels: C++, Type Analysis, defect

#4013 Fix except+* exception handling
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  tests/errors/cppexc_non_extern.pyx
  tests/run/cpp_exception_declaration_compatibility.srctree
  tests/run/cpp_exceptions_utility_code.pyx
Labels: C++, Cython Language Feature, defect

#4238 Glossary was broken
  docs/src/userguide/glossary.rst
  docs/src/userguide/wrapping_CPlusPlus.rst
Labels: Documentation, defect

#4239 delete -> delete[] in cpp_nonstdint test
  tests/run/cpp_nonstdint.h
Labels: Testing, defect

#4199 Don't let Py-class annotations set a type
  Cython/Compiler/ExprNodes.py
  tests/run/pep526_variable_annotations.py
  tests/run/pyclass_annotations_pep526.py
Labels: Error Reporting, Type Analysis, defect

#4244 Update error message in documentation
  docs/src/userguide/language_basics.rst
Labels: Documentation

#4248 Set is_cython_module on annotations correctly
  Cython/Compiler/ParseTreeTransforms.py
  tests/run/annotation_typing.pyx
Labels: Type Analysis, defect

#4251 Update numpy_tutorial.rst
  docs/src/userguide/numpy_tutorial.rst
Labels: Documentation, R: worksforme

#4256 fix call to run_distutils
  Cython/Debugger/Tests/TestLibCython.py
Labels: Testing, defect
