Repository cython/cython, pull requests merged in 2021-09, with the labels that each got.

#4349 Fix C++ bool coercion where no operator bool exists
  Cython/Compiler/ExprNodes.py
  tests/errors/cpp_bool.pyx
Labels: C++, Type Analysis

#4363 Fix a couple of trivial typos
  docs/src/userguide/language_basics.rst
  tests/errors/cpp_bool.pyx
Labels: Documentation

#4361 Fix maybe uninitialized `value` in get_value and get_value_no_default.
  Cython/Includes/cpython/contextvars.pxd
Labels: defect, Code Generation

#4380 Removed usused "FetchCommonPointer" utility code
  Cython/Utility/CommonStructures.c
  Cython/Utility/ModuleSetupCode.c
Labels: cleanup

#4370 Avoid unnecessary binding of fused functions
  Cython/Utility/CythonFunction.c
  tests/run/fused_bound_functions.py
Labels: enhancement, Code Generation

#4378 Avoid AddTraceback if stringtab isn't set up
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  tests/run/numpy_import_array_error.srctree
Labels: defect, Code Generation, cleanup

#4376 Fix the name of attributes in the common module
  Cython/Utility/CommonStructures.c
  tests/run/common_utility_types.srctree
Labels: defect, Python Semantics, Code Generation
