Repository cython/cython, pull requests merged in 2022-11, with the labels that each got.

#5115 Wheel CI: Update cibuildwheel to v2.11.2
  .github/workflows/wheels.yml
Labels: Build System

#5108 Docs: Improve documentation about error return values
  docs/src/userguide/language_basics.rst
Labels: Documentation

#5105 Optimized implementation of bound c methods
  Cython/Compiler/ExprNodes.py
  Cython/Utility/ObjectHandling.c
Labels: enhancement, Optimization, Code Generation

#5040 Fix linkage for `cdef public` functions in C++ mode
  Cython/Compiler/ModuleNode.py
  docs/examples/tutorial/embedding/embedded.pyx
  tests/compile/excvalcheck.h
  tests/compile/nogil.h
  tests/run/cpp_extern.srctree
Labels: C++, Code Generation

#4629 cython, cythonize commands return error when file does not exist
  Cython/Build/Cythonize.py
  Cython/Compiler/CmdLine.py
  Cython/Compiler/Main.py
  Cython/Compiler/Tests/TestCmdLine.py
  Tools/ci-run.sh
  test-requirements-27.txt
  test-requirements-pypy27.txt
  tests/run/cython_no_files.srctree
Labels: enhancement, Error Reporting

#5078 Run GCC 11 tests with the most recent language standard
  .github/workflows/ci.yml
  Cython/Utility/ModuleSetupCode.c
Labels: Testing

#3221 Cppclass nested classes
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Symtab.py
  tests/run/cpp_nested_classes.pyx
Labels: C++, feature, enhancement

#4692 Remove "assignable" requirement from cpp_locals
  Cython/Utility/CppSupport.cpp
  tests/run/cpp_locals_directive.pyx
Labels: C++, enhancement

#5046 Clean up issues with dataclasses and inheritance
  Cython/Compiler/Dataclass.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Symtab.py
  Tools/make_dataclass_tests.py
  tests/errors/dataclass_e6.pyx
  tests/errors/dataclass_w1.pyx
  tests/errors/dataclass_w1_othermod.pxd
  tests/run/test_dataclasses.pyx
Labels: defect, Code Generation, Error Reporting

#5140 Pin line_profiler version to <4
  test-requirements-cpython.txt
Labels: Testing

#5135 Allow returning const types.
  Cython/Compiler/Nodes.py
  tests/run/return.pyx
Labels: defect, Code Generation

#5128 Remove HTML template support from Tempita
  Cython/Tempita/_tempita.py
Labels: cleanup, tempita

#5145 Backport support for PEP-623 to 0.29.x
  .github/workflows/ci.yml
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation

#5031 Avoid triggering type-check assert for cyfuncs [0.29.x]
  Cython/Utility/ObjectHandling.c
  Tools/ci-run.sh
Labels: defect, Code Generation

#5148 allow suggestions on AttributeError for PyPy in doctests
  .github/workflows/ci.yml
  tests/run/py_classbody.py
Labels: Testing

#5152 Fix fastcall test
  tests/run/fastcall.pyx
Labels: Testing

#5154 Use setuptools>60 for cpython3.12, skip unicode test on PyPy and 3.12+
  Tools/ci-run.sh
  runtests.py
  test-requirements-312.txt
  tests/pypy_implementation_detail_bugs.txt
Labels: defect, Testing

#5157 missing load_factor method on unordered_multimap
  Cython/Includes/libcpp/unordered_map.pxd
Labels: C++, enhancement, Library

#5139 Fix quadratic-time ModuleNode.sort_types_by_inheritance
  Cython/Compiler/ModuleNode.py
Labels: performance, Type Analysis
