Repository cython/cython, pull requests merged in 2022-12, with the labels that each got.

#5056 Refactor module state to always use struct
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/StringTools.c
Labels: Code Generation, cleanup

#5119 Docs: Migrate fused types userguide to pure python
  docs/examples/userguide/fusedtypes/char_or_float.py
  docs/examples/userguide/fusedtypes/conditional_gil.pyx
  docs/examples/userguide/fusedtypes/indexing.py
  docs/examples/userguide/fusedtypes/indexing.pyx
  docs/examples/userguide/fusedtypes/pointer.py
  docs/examples/userguide/fusedtypes/pointer.pyx
  docs/examples/userguide/fusedtypes/type_checking.py
  docs/examples/userguide/fusedtypes/type_checking.pyx
  docs/src/tutorial/pure.rst
  docs/src/userguide/fusedtypes.rst
Labels: Documentation

#5142 Relax `nogil_check()` of `SliceIndexNode` to support array initialisation
  Cython/Compiler/ExprNodes.py
  tests/errors/nogil.pyx
  tests/run/nogil.pyx
Labels: enhancement, Code Generation

#5097 Accept both 'int' and 'long' for 'x: int' annotations in Py2
  CHANGES.rst
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/ModuleSetupCode.c
  docs/src/userguide/migrating_to_cy30.rst
  docs/src/userguide/source_files_and_compilation.rst
  tests/run/cython3.pyx
  tests/run/cython3_no_unicode_literals.pyx
Labels: defect, Python Semantics

#5021 Improve detection of C complex.h
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/Complex.c
Labels: enhancement, Code Generation

#5016 Add the `cpow` directive to bring Cython `**` close to Python
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Options.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/TypeInference.py
  Cython/Utility/Complex.c
  docs/src/userguide/cpow_table.csv
  docs/src/userguide/migrating_to_cy30.rst
  docs/src/userguide/source_files_and_compilation.rst
  tests/run/cpow.pyx
  tests/run/powop.pyx
Labels: defect, Python Semantics, P: blocker

#5164 [0.29.x] Added PyUnicode_AsUTF8AndSize to cpython imports
  Cython/Includes/cpython/unicode.pxd
Labels: enhancement, Library

#5167 Fix error from combination of two Complex.c changes
  Cython/Utility/Complex.c
Labels: defect, Code Generation

#5165 Docs: Document type qualifiers
  docs/src/userguide/language_basics.rst
Labels: Documentation

#5168 Support 2 and 3 arg __[ri]pow__
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/TypeSlots.py
  docs/src/userguide/special_methods.rst
  runtests.py
  tests/errors/e_argdefault.pyx
  tests/run/special_methods_T561.pyx
  tests/run/special_methods_T561_py38.pyx
Labels: defect, Python Semantics, Pure Python Mode

#5181 numpy.int -> numpy.int_
  tests/run/numpy_parallel.pyx
  tests/run/numpy_test.pyx
Labels: Testing

#5180 Remove unnecessary OrderedDict usage for CpdefEnums
  Cython/Utility/CpdefEnums.pyx
Labels: Code Generation, cleanup

#5175 Fix named expression tests windows
  .github/workflows/ci.yml
  Tools/ci-run.sh
  tests/run/cpp_extern.srctree
  tests/run/test_named_expressions.py
Labels: Testing

#5187 Change how memoryviewslice/array has sequence flag set
  Cython/Compiler/Options.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/TypeSlots.py
  Cython/Utility/MemoryView.pyx
  Cython/Utility/ModuleSetupCode.c
  tests/compile/fused_redeclare_T3111.pyx
Labels: Code Generation

#5190 [0.29.x] numpy.int -> numpy.int_
  tests/run/numpy_parallel.pyx
  tests/run/numpy_test.pyx
Labels: Testing, numpy
