Repository cython/cython, pull requests merged in 2022-07, with the labels that each got.

#4823 includes/cpython: Fix newfunc to use PyObject* for args/kwargs instead of object
  Cython/Includes/cpython/object.pxd
Labels: defect, Library

#4625 Port pyximport to importlib machinery with git history
  pyximport/_pyximport2.py
  pyximport/_pyximport3.py
  pyximport/pyximport.py
Labels: defect, Python Semantics

#4868 Fix syntax for ellipsis
  Cython/Compiler/Lexicon.py
  Cython/Compiler/Parsing.py
  Cython/Compiler/Tests/TestGrammar.py
  tests/compile/fromimport.pyx
  tests/compile/fromimport_star.pyx
  tests/errors/incomplete_varadic.pyx
Labels: Parsing, defect

#4872 avoid null dereference in __Pyx_KwValues_FASTCALL
  Cython/Utility/FunctionArguments.c
Labels: Code Generation, cleanup

#4863 Notes about embedding and portable applications
  docs/src/tutorial/embedding.rst
  docs/src/userguide/external_C_code.rst
Labels: Documentation

#4847 Don't generate multiple "CoerceToBooleanNode" layers
  Cython/Compiler/ExprNodes.py
Labels: Code Generation, cleanup

#4606 Fix annotation type analysis for Python "typing" types
  Cython/Compiler/Builtin.py
  Cython/Compiler/Dataclass.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  docs/examples/userguide/extension_types/dataclass.pyx
  tests/errors/dataclass_e1.pyx
  tests/errors/dataclass_e5.pyx
  tests/errors/e_typing_errors.pyx
  tests/errors/e_typing_optional.py
  tests/run/annotation_typing.pyx
  tests/run/cdef_class_dataclass.pyx
  tests/run/cdef_setitem_T284.pyx
  tests/run/delete.pyx
  tests/run/pep526_variable_annotations.py
  tests/run/pep526_variable_annotations_cy.pyx
  tests/run/pure_cdef_class_dataclass.py
Labels: defect, P: blocker, Type Analysis

#4879 Add a note about cythonize in the quickstart documentation
  docs/src/quickstart/build.rst
Labels: Documentation

#4849 Error on memoryview argument capture on 0.29.x
  Cython/Compiler/Nodes.py
  tests/memoryview/memslice.pyx
Labels: defect, Code Generation

#4850 Disable co_varnames identity check on Python 3.11
  tests/run/tuple_constants.pyx
Labels: defect, Testing

#4845 Avoid conflict between propery names and function variables
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Visitor.py
  tests/run/decorators.pyx
Labels: defect, Type Analysis

#4834 Fixed over-zealous optimization of __Pyx_PyObject_Append
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  tests/run/append.pyx
Labels: defect, Optimization

#4869 Handle extern PyVarObjects
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/ImportExport.c
  runtests.py
  tests/errors/builtin_type_inheritance.pyx
  tests/pypy_bugs.txt
  tests/run/builtin_type_inheritance_T608.pyx
  tests/run/builtin_type_inheritance_T608_py2only.pyx
  tests/run/extern_varobject_extensions.srctree
Labels: enhancement, Error Reporting

#4846 Refactor parsing of named expressions
  Cython/Compiler/Parsing.pxd
  Cython/Compiler/Parsing.py
Labels: Parsing, cleanup

#4817 Make memoryviewslice and cython.array be collections.abc.Sequence
  Cython/Utility/MemoryView.pyx
  tests/compile/fused_redeclare_T3111.pyx
  tests/memoryview/cythonarray.pyx
  tests/memoryview/memoryview.pyx
Labels: enhancement, Python Semantics

#4814 Enable parenthesized context managers
  Cython/Compiler/Parsing.py
  tests/run/test_grammar.py
Labels: Parsing

#4894 Account for possible struct padding when calculating itemsize
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ImportExport.c
Labels: defect, Error Reporting

#4780 CI: Remove allow_failures for Python 3.11
  .github/workflows/ci.yml
Labels: cleanup, Testing

#4900 Improve test coverage of special methods with type conversions
  tests/run/special_methods_T561.pyx
Labels: Testing

#4917 Update macos version for github actions
  .github/workflows/ci.yml
Labels: Testing

#4910 add missing unicode APIs
  Cython/Includes/cpython/unicode.pxd
Labels: enhancement, Library

#4922 Remove unused function "looking_at_call" from parser
  Cython/Compiler/Parsing.pxd
  Cython/Compiler/Parsing.py
Labels: Parsing, cleanup

#4914 [0.29] Add configuration for nogil Python (gh-4912)
  Cython/Utility/ModuleSetupCode.c
  tests/compile/buildenv.pyx
Labels: feature, Code Generation

#4903 Backport noexcept to Cython 0.29.x
  Cython/Compiler/Parsing.py
  docs/src/userguide/language_basics.rst
  tests/compile/excvaldecl.pyx
Labels: enhancement, Python Semantics

#4906 [0.29] Add --module-name argument to cython command
  Cython/Compiler/CmdLine.py
  Cython/Compiler/Main.py
  Cython/Compiler/Tests/TestCmdLine.py
  tests/compile/module_name_arg.srctree
Labels: feature, Build System

#4324 Make GitHub Actions work on Windows
  .github/workflows/ci.yml
  .gitignore
  Tools/ci-run.sh
  runtests.py
  test-requirements-27.txt
  test-requirements-34.txt
  tests/windows_bugs_39.txt
Labels: Testing

#4930 Fix error where import * tried to overwrite a macro
  Cython/Utility/MemoryView.pyx
  Cython/Utility/MemoryView_C.c
  tests/memoryview/memslice.pyx
Labels: defect, Type Analysis

#4929 Reallow capture of memoryview arguments
  Cython/Compiler/Nodes.py
  tests/memoryview/memslice.pyx
Labels: defect, Error Reporting

#4916 implement the depfile command-line option for the "cython" tool
  Cython/Build/Dependencies.py
  Cython/Compiler/CmdLine.py
  Cython/Compiler/Main.py
  Cython/Compiler/Options.py
  Cython/Utils.py
  tests/build/depfile_package_cython.srctree
  tests/build/depfile_package_cythonize.srctree
Labels: Build System

#4902 Make Cython async functions set CO_COROUTINE and CO_ASYNC_GENERATOR code flags
  Cython/Compiler/ExprNodes.py
  Cython/Utility/ModuleSetupCode.c
  tests/run/test_coroutines_pep492.pyx
Labels: defect, Python Semantics

#4908 Fix initialization of init=False dataclass fields
  Cython/Compiler/Dataclass.py
  tests/run/pure_cdef_class_dataclass.py
Labels: defect, Python Semantics

#4938 Allow C code assertions in tests by defining regular expressions in module directives
  Cython/Compiler/Options.py
  Cython/Compiler/Parsing.py
  Cython/Compiler/Pipeline.py
  Cython/TestUtils.py
  tests/compile/c_directives.pyx
  tests/run/c_file_validation.srctree
Labels: feature, Testing

#4935 Don't call __Pyx_ImportNumPyArrayTypeIfAvailable for every fused def function
  Cython/Utils.py
  tests/compile/fused_buffers.pyx
  tests/compile/fused_no_numpy.pyx
Labels: defect, Code Generation

#4603 Add var_entry for "special" modules (e.g. typing)
  Cython/Compiler/Builtin.py
  tests/run/cdef_class_dataclass.pyx
  tests/run/pep526_variable_annotations.py
Labels: defect, Type Analysis

#4925 Use standard C or C++ atomics for memoryviews
  Cython/Utility/MemoryView_C.c
Labels: enhancement, Code Generation
