Repository cython/cython, pull requests merged in 2022-04, with the labels that each got.

#4701 use wrapperbase for descr doc on PyPy>=7.3.9
  Cython/Compiler/Nodes.py
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation

#4715 Fix typo in tests/build/cythonize_cython.srctree
  tests/build/cythonize_cython.srctree
Labels: defect, Testing

#4723 Fix possible exception reset in the exception handling code
  Cython/Utility/Exceptions.c
Labels: defect, Code Generation

#4728 Force EncodedString on dataclass types
  Cython/Compiler/Dataclass.py
  tests/run/cdef_class_dataclass.pyx
Labels: defect

#4729 Fix tiny code quoting error in docs
  docs/src/userguide/extension_types.rst
Labels: Documentation

#4732 Test for object.__getstate__ in pickling
  Cython/Utility/ExtensionTypes.c
Labels: defect, Code Generation

#4727 Fix UnionType.__setattr__
  Cython/Shadow.py
Labels: defect, Pure Python Mode

#4735 Disable CYTHON_FAST_PYCALL on Py3.10 (0.29.x)
  Cython/Utility/ModuleSetupCode.c
  tests/run/call_trace_gh4609.srctree
Labels: defect, Code Generation

#4742 Revert "Avoid acquiring the GIL at the end of nogil functions (GH-3556)"
  Cython/Compiler/Code.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation

#4739 Avoid error if type doesn't have __getstate__
  Cython/Utility/ExtensionTypes.c
Labels: defect, Code Generation

#4740 Allow None to coerce to C types separately from other object values.
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/ModuleSetupCode.c
  tests/run/unicodemethods.pyx
Labels: defect, Python Semantics

#4734 Avoid nullptr math undefined behaviour in ObjectHandling.c
  Cython/Utility/ObjectHandling.c
Labels: defect, Code Generation

#4528 fix incorrect iterator implementation
  Cython/Includes/libcpp/deque.pxd
  Cython/Includes/libcpp/forward_list.pxd
  Cython/Includes/libcpp/list.pxd
  Cython/Includes/libcpp/map.pxd
  Cython/Includes/libcpp/set.pxd
  Cython/Includes/libcpp/string.pxd
  Cython/Includes/libcpp/unordered_map.pxd
  Cython/Includes/libcpp/unordered_set.pxd
  Cython/Includes/libcpp/vector.pxd
  tests/errors/cpp_no_const_iterator_conversion.pyx
  tests/run/cpp_iterators.pyx
  tests/run/cpp_stl_map.pyx
  tests/run/cpp_stl_set.pyx
Labels: C++, enhancement, Library

#4746 Add mt19937 random number generator to libcpp.
  Cython/Includes/libcpp/random.pxd
  tests/run/cpp_stl_random.pyx
Labels: C++, enhancement, Library

#4743 Tests for PR4740
  tests/run/unicodemethods.pyx
Labels: defect, Python Semantics
