Repository cython/cython, pull requests merged in 2022-06, with the labels that each got.

#4824 DOC Fixes link to init methods in extension types user guide
  docs/src/userguide/extension_types.rst
Labels: Documentation

#4762 Add distributions to `libcpp.random`.
  Cython/Includes/libcpp/random.pxd
  tests/run/cpp_stl_random.pyx
Labels: C++, enhancement, Library

#4820 MNT: always require va_start to have two arguments
  Cython/Utility/MemoryView_C.c
Labels: defect, Code Generation

#4826 Update preprocessing warning to be compatible with MSVC
  Cython/Compiler/Nodes.py
Labels: defect, Code Generation, limited api

#4854 Fix GCC -Wconversion warning
  Cython/Utility/CythonFunction.c
  Cython/Utility/StringTools.c
Labels: defect, Code Generation

#4537 Docs: Migrate special_methods.rst to pure python
  docs/examples/userguide/special_methods/total_ordering.py
  docs/examples/userguide/special_methods/total_ordering.pyx
  docs/src/userguide/special_methods.rst
Labels: Documentation

#4865 Docs: don't say cdef functions exist in module dict
  docs/src/userguide/sharing_declarations.rst
Labels: Documentation

#4864 Fix tuple multiplication in MergedSequenceNode
  Cython/Compiler/ExprNodes.py
  tests/run/pep448_extended_unpacking.pyx
Labels: defect, Optimization
