Repository cython/cython, pull requests merged in 2022-10, with the labels that each got.

#5002 Implement reversed C++ iteration
  Cython/Compiler/ExprNodes.py
  tests/run/cpp_iterators.pyx
Labels: C++, feature

#4991 PEP614 decorators
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.py
  tests/errors/e_decorators.pyx
  tests/errors/w_uninitialized.pyx
  tests/run/decorators.pyx
  tests/run/test_grammar.py
Labels: feature, Python Semantics

#5018 "Fix" an exception formatting issue on Py2
  Cython/Utility/CythonFunction.c
Labels: defect, Code Generation

#5065 Docs: Fix example in buffer user guide
  docs/examples/userguide/buffer/matrix_with_buffer.pyx
Labels: Documentation

#5068 Fixed missed binop self types
  Cython/Compiler/TypeSlots.py
  tests/run/binop_reverse_methods_GH2056.pyx
Labels: defect, Python Semantics

#5069 Docs: Migrate buffer userguide to pure python
  docs/examples/userguide/buffer/matrix.py
  docs/examples/userguide/buffer/matrix.pyx
  docs/examples/userguide/buffer/matrix_with_buffer.py
  docs/examples/userguide/buffer/matrix_with_buffer.pyx
  docs/examples/userguide/buffer/view_count.py
  docs/examples/userguide/buffer/view_count.pyx
  docs/src/userguide/buffer.rst
Labels: Documentation

#5074 Fix PYPY_VERSION_HEX/PYPY_VERSION_NUM typo
  Cython/Utility/ModuleSetupCode.c
Labels: defect

#4904 Remove "from x cimport class C"
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.pxd
  Cython/Compiler/Parsing.py
Labels: cleanup

#4905 [0.29] deprecation warning for "from x cimport class A" syntax
  Cython/Compiler/Parsing.py
Labels: cleanup

#5083 always set CYTHON_UPDATE_DESCRIPTOR_DOC to 0 on PyPy
  Cython/Utility/ModuleSetupCode.c
Labels: cleanup, PyPy

#5086 Fix various clang warnings
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/Exceptions.c
  Cython/Utility/ObjectHandling.c
Labels: Code Generation

#5093 Recommend Cython 3 for pure-Python syntax
  docs/src/two-syntax-variants-used
Labels: Documentation

#5057 Restore 'int'->'object' for now
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  docs/src/userguide/migrating_to_cy30.rst
  tests/run/annotation_typing.pyx
Labels: defect, Python Semantics

#5101 Add missing C++17/20 STL functions and methods
  Cython/Includes/libcpp/map.pxd
  Cython/Includes/libcpp/numeric.pxd
  Cython/Includes/libcpp/set.pxd
  Cython/Includes/libcpp/string.pxd
  Cython/Includes/libcpp/unordered_map.pxd
  Cython/Includes/libcpp/unordered_set.pxd
  tests/run/cpp_stl_associated_containers_contains_cpp20.pyx
  tests/run/cpp_stl_numeric_ops_cpp17.pyx
  tests/run/cpp_stl_numeric_ops_cpp20.pyx
  tests/run/cpp_stl_string_cpp20.pyx
Labels: C++, Library

#5098 Fix faulty calls to Context
  Cython/Build/Dependencies.py
  Cython/Build/Inline.py
Labels: Build System, cleanup

#5095 Docs: Update documentation after introduction of noexcept
  docs/src/tutorial/clibraries.rst
  docs/src/userguide/language_basics.rst
Labels: Documentation

#5106 Update CCache script version
  .github/workflows/ci.yml
Labels: Testing

#5107 Use double quotes for arguments in timeit
  docs/src/tutorial/cython_tutorial.rst
Labels: Documentation
