Repository cython/cython, pull requests merged in 2022-09, with the labels that each got.

#5004 prevent more unused variable warnings
  Cython/Compiler/ExprNodes.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/CommonStructures.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/Exceptions.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/Optimize.c
Labels: defect, Code Generation

#4977 ci-run.sh: run msvc build with multiple processes
  Tools/ci-run.sh
Labels: enhancement, Testing

#4988 Allow bound cfuncs to be coerced to object
  Cython/Compiler/ExprNodes.py
  tests/run/cfunc_convert.pyx
Labels: feature, Cython Language Feature

#4996 Make sure we call __del__ for final types
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/TypeSlots.py
  runtests.py
  tests/run/pep442_tp_finalize.pyx
  tests/run/pep442_tp_finalize_cimport.srctree
Labels: defect, Python Semantics, Cython Language Feature

#4955 Try to use test_dataclass from CPython
  Tools/dataclass_test_data/test_dataclasses.py
  Tools/make_dataclass_tests.py
  runtests.py
  tests/run/test_dataclasses.pxi
  tests/run/test_dataclasses.pyx
Labels: Testing

#4670 [ENH] Propagate exceptions from `cdef` functions by default
  Cython/Compiler/Nodes.py
  Cython/Compiler/Parsing.pxd
  Cython/Compiler/Parsing.py
  Cython/Compiler/PyrexTypes.py
  Cython/Includes/cpython/time.pxd
  Cython/Utility/MemoryView.pyx
  docs/src/userguide/language_basics.rst
  docs/src/userguide/migrating_to_cy30.rst
  tests/build/cythonize_options.srctree
  tests/compile/branch_hints.pyx
  tests/compile/cpp_nogil.pyx
  tests/compile/declarations.srctree
  tests/compile/publicapi_pxd_mix.pxd
  tests/compile/publicapi_pxd_mix.pyx
  tests/errors/cfuncptr.pyx
  tests/errors/e_excvalfunctype.pyx
  tests/errors/e_nogilfunctype.pyx
  tests/errors/nogil.pyx
  tests/errors/nogilfunctype.pyx
  tests/memoryview/cythonarray.pyx
  tests/memoryview/memoryview_acq_count.srctree
  tests/memoryview/memslice.pyx
  tests/memoryview/numpy_memoryview.pyx
  tests/run/builtin_abs.pyx
  tests/run/cfunc_convert.pyx
  tests/run/cpdef_void_return.pyx
  tests/run/cpp_classes.pyx
  tests/run/cpp_classes_def.pyx
  tests/run/cpp_exceptions_nogil.pyx
  tests/run/cpp_function_lib.pxd
  tests/run/cpp_stl_function.pyx
  tests/run/exceptionpropagation.pyx
  tests/run/exceptions_nogil.pyx
  tests/run/line_trace.pyx
  tests/run/nogil.pyx
  tests/run/nogil_conditional.pyx
  tests/run/parallel.pyx
  tests/run/sequential_parallel.pyx
  tests/run/trace_nogil.pyx
  tests/run/type_inference.pyx
  tests/run/with_gil.pyx
  tests/run/with_gil_automatic.pyx
  tests/run/withnogil.pyx
  tests/testsupport/cythonarrayutil.pxi
Labels: enhancement, Python Semantics

#5026 Remove dataclass tests that used mutability
  Tools/make_dataclass_tests.py
  tests/run/test_dataclasses.pyx
Labels: Testing

#5032 Use proper SPDX identifier
  setup.py
Labels: Documentation

#4536 fix incorrect operator lookup for postincrement
  Cython/Compiler/ExprNodes.py
  docs/src/userguide/migrating_to_cy30.rst
  tests/errors/cpp_increment.pyx
Labels: C++, enhancement

#5025 [Ticket 2940] fix mangling for .pxd cdef public functions
  Cython/Compiler/Symtab.py
  tests/compile/pxd_mangling_names.srctree
  tests/pypy2_bugs.txt
Labels: defect, Code Generation

#5014 Fix bug with complex powers of negative numbers
  Cython/Utility/Complex.c
  tests/run/complex_numbers_T305.pyx
Labels: defect

#5038 GitHub Workflows security hardening
  .github/workflows/ci.yml
  .github/workflows/wheels.yml
Labels: enhancement, Build System

#3831 Fix coverage in src layout with test.
  Cython/Coverage.py
  tests/run/coverage_cmd_src_pkg_layout.srctree
Labels: enhancement, Coverage

#4957 Allow empty args to dataclass and field directives
  Cython/Compiler/Dataclass.py
  Cython/Compiler/ParseTreeTransforms.py
  Tools/make_dataclass_tests.py
  tests/run/test_dataclasses.pyx
Labels: defect, Cython Language Feature

#5048 Update pyxcodewriter.indenter to use `with`
  Cython/Compiler/Code.py
  Cython/Compiler/FusedNode.py
Labels: cleanup

#5045 Fix recursive repr on cdef dataclasses
  Cython/Compiler/Dataclass.py
  Tools/make_dataclass_tests.py
  tests/run/test_dataclasses.pyx
Labels: defect, Cython Language Feature
