Repository cython/cython, pull requests merged in 2023-11, with the labels that each got.

#5679 Add list of tests that work with Py_LIMITED_API
  Cython/Utility/ModuleSetupCode.c
  runtests.py
  tests/test_in_limited_api.txt
Labels: Testing, limited api

#5695 Fix limited api float
  Cython/Utility/Optimize.c
  tests/run/isolated_limited_api_tests.srctree
Labels: limited api

#5777 Stop fallback indexing code using PySequence_*Item first
  Cython/Utility/ObjectHandling.c
  tests/pypy_bugs.txt
  tests/run/index.pyx
Labels: defect, Python Semantics

#5698 Do no-type-slots dictoffset check as python lookup
  Cython/Utility/ExtensionTypes.c
Labels: defect, Code Generation, PyPy, limited api

#5791 Fix C++17 error: standard attributes in middle of decl-specifiers (CYTHON_UNUSED)
  Cython/Utility/FunctionArguments.c
Labels: defect, Code Generation

#5796 Fix issue with cpdef functions and cimport_from_pyx
  Cython/Compiler/FusedNode.py
  tests/run/cimport_from_pyx.srctree
Labels: defect

#5464 Add warning about embedding + multiprocessing
  docs/src/tutorial/embedding.rst
Labels: Documentation

#5778 Add tests for some of the contents of Shadow.py
  Cython/Compiler/Options.py
  Cython/Shadow.py
  Cython/Tests/TestShadow.py
Labels: Testing, Pure Python Mode

#5803 Add missing directives to Shadow.py
  Cython/Shadow.py
Labels: Pure Python Mode

#5805 Fix indexing of self.args when passing Python object as varargs parameter
  Cython/Compiler/ExprNodes.py
Labels: defect, Error Reporting

#5642 Error if Cython enum is used outside a typed context
  Cython/Compiler/ExprNodes.py
  tests/errors/e_cenum_expr.pyx
Labels: Error Reporting

#5699 Fix "except Exception" in limited api
  Cython/Compiler/Builtin.py
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/TypeSlots.py
  tests/run/isolated_limited_api_tests.srctree
Labels: Code Generation, limited api

#5515 Cleanup a lot of casts to char*
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/CommonStructures.c
  Cython/Utility/Coroutine.c
  Cython/Utility/ImportExport.c
  Cython/Utility/MemoryView.pyx
  Cython/Utility/MemoryView_C.c
  Cython/Utility/TypeConversion.c
Labels: Code Generation, cleanup

#5809 Check for MSVC when checking for complex support on C11
  Cython/Utility/Complex.c
Labels: defect, Code Generation

#5815 Remove allowed_failure from Python 3.12
  .github/workflows/ci.yml
  runtests.py
Labels: Testing

#5819 update no-compile install from source (closes #5694)
  docs/src/quickstart/install.rst
  setup.py
Labels: Documentation

#5785 Optimize numerical operations with python integer variable
  Cython/Compiler/Optimize.py
  tests/run/pyintop.pyx
Labels: performance, enhancement, Optimization, Code Generation, Pure Python Mode

#5829 Remove checks for WITH_THREAD
  Cython/Compiler/Code.py
  Cython/Utility/Buffer.c
  Cython/Utility/Exceptions.c
  Cython/Utility/MemoryView_C.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Profile.c
Labels: cleanup

#5824 Remove compatibility code not needed anymore
  Cython/Build/Cythonize.py
  Cython/Build/Dependencies.py
  Cython/Build/Inline.py
  Cython/Build/IpythonMagic.py
  Cython/Build/Tests/TestCythonizeArgsParser.py
  Cython/Build/Tests/TestDependencies.py
  Cython/Build/Tests/TestIpythonMagic.py
  Cython/Build/__init__.py
  Cython/Compiler/Annotate.py
  Cython/Compiler/CmdLine.py
  Cython/Compiler/Code.py
  Cython/Compiler/Errors.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Interpreter.py
  Cython/Compiler/Main.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Scanning.py
  Cython/Compiler/StringEncoding.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/Tests/TestCmdLine.py
  Cython/Compiler/Tests/TestStringEncoding.py
  Cython/Compiler/TreeFragment.py
  Cython/Compiler/TypeInference.py
  Cython/Compiler/Visitor.py
  Cython/Debugger/libcython.py
  Cython/Debugger/libpython.py
  Cython/Distutils/build_ext.py
  Cython/Distutils/extension.py
  Cython/Distutils/old_build_ext.py
  Cython/Plex/Machines.py
  Cython/Shadow.py
  Cython/StringIOTree.py
  Cython/Tempita/_looper.py
  Cython/Tempita/_tempita.py
  Cython/Tempita/compat3.py
  Cython/Tests/TestCythonUtils.py
  Cython/Tests/xmlrunner.py
  Cython/Utility/MemoryView.pyx
  Cython/Utils.py
  pyximport/_pyximport2.py
  tests/compile/fused_redeclare_T3111.pyx
  tests/errors/pure_warnings.py
  tests/run/pyintop.pyx
Labels: cleanup

#5827 Make language level 3 the default
  Cython/Build/Cythonize.py
  Cython/Build/Inline.py
  Cython/Build/Tests/TestCythonizeArgsParser.py
  Cython/Compiler/Builtin.py
  Cython/Compiler/CmdLine.py
  Cython/Compiler/Code.pxd
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FlowControl.pxd
  Cython/Compiler/FlowControl.py
  Cython/Compiler/Lexicon.py
  Cython/Compiler/Main.py
  Cython/Compiler/ParseTreeTransforms.pxd
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.pxd
  Cython/Compiler/Parsing.py
  Cython/Compiler/Pythran.py
  Cython/Compiler/Scanning.pxd
  Cython/Compiler/Scanning.py
  Cython/Compiler/Tests/TestCmdLine.py
  Cython/Compiler/TreeFragment.py
  Cython/Compiler/Visitor.pxd
  Cython/Compiler/Visitor.py
  Cython/Plex/Actions.pxd
  Cython/Plex/Actions.py
  Cython/Plex/DFA.pxd
  Cython/Plex/Machines.py
  Cython/Plex/Scanners.py
  Cython/Plex/Transitions.py
  Cython/StringIOTree.py
  Cython/Tempita/_tempita.py
  Cython/Utility/MemoryView.pyx
  setup.py
  tests/errors/string_assignments.pyx
  tests/run/public_fused_types.srctree
Labels: cleanup

#5830 Map Python "int" type to PyLong.
  Cython/Compiler/Builtin.py
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/Parsing.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/Visitor.py
  Cython/Shadow.py
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/Optimize.c
  docs/examples/userguide/fusedtypes/char_or_float.py
  docs/examples/userguide/fusedtypes/char_or_float.pyx
  tests/compile/pylong.pyx
  tests/errors/dataclass_e5.pyx
  tests/run/annotation_typing.pyx
  tests/run/builtin_py3.pyx
  tests/run/fused_types.pyx
  tests/run/isinstance.pyx
  tests/run/powop.pyx
  tests/run/type_inference.pyx
Labels: enhancement, Python Semantics, Type Analysis

#5832 Partially disable trashcan test in PyPy
  tests/run/trashcan.pyx
Labels: Testing, PyPy

#5760 cython magic: extract style, body, not full HTML document
  Cython/Build/IpythonMagic.py
Labels: Tools

#5835 Remove patch utility code in Coroutine.c
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Utility/Coroutine.c
Labels: cleanup

#5847 Clean up a few more casts to non-const char*
  Cython/Utility/CythonFunction.c
Labels: cleanup

#5844 Infer the result type of builtin numeric binary operations
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/PyrexTypes.py
  tests/errors/reversed_literal_pyobjs.pyx
  tests/run/type_inference.pyx
  tests/run/type_inference_ll2.pyx
Labels: enhancement, Type Analysis

#5841 Drop PyFPE macros
  Cython/Utility/Optimize.c
  tests/run/isolated_limited_api_tests.srctree
Labels: cleanup, limited api

#5798 Further limited API fixes
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Optimize.py
  Cython/Utility/CythonFunction.c
  Cython/Utility/ImportExport.c
  Cython/Utility/MemoryView_C.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/StringTools.c
  Cython/Utility/TypeConversion.c
  tests/test_in_limited_api.txt
Labels: enhancement, limited api

#5381 Support match_args in cdef dataclasses
  Cython/Compiler/Dataclass.py
  Tools/make_dataclass_tests.py
  tests/run/test_dataclasses.pyx
Labels: enhancement, Code Generation

#5857 Fix dataclass comparison operators and enable tests
  Cython/Compiler/Dataclass.py
  Tools/make_dataclass_tests.py
  tests/run/test_dataclasses.pyx
Labels: defect, Code Generation

#5867 Note on pure-Python mode and Numpy arrays
  docs/src/tutorial/numpy.rst
Labels: Documentation

#5866 Speed up fstrings
  Cython/Compiler/ExprNodes.py
  Cython/Utility/StringTools.c
Labels: enhancement, Code Generation

#5865 Implement return type inference for methods of builtin types
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Tests/TestBuiltin.py
  Cython/Compiler/TypeInference.py
  tests/run/bytesmethods.pyx
  tests/run/strmethods.pyx
  tests/run/strmethods_ll2.pyx
  tests/run/type_inference.pyx
Labels: enhancement, Type Analysis

#4980 [Docs] Provide tables listing basic cython types
  docs/src/userguide/language_basics.rst
Labels: Documentation

#5864 Document user-selectable C macros
  docs/src/userguide/external_C_code.rst
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#5875 Delete some Python 2 module init function code
  Cython/Compiler/ModuleNode.py
Labels: cleanup

#5882 Add separate macro guard "CYTHON_ASSUME_SAFE_SIZE"
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  Cython/Utility/Builtins.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/FunctionArguments.c
  Cython/Utility/ImportExport.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Optimize.c
  Cython/Utility/StringTools.c
  Cython/Utility/TypeConversion.c
  docs/src/userguide/source_files_and_compilation.rst
Labels: enhancement, Code Generation

#5879 Use `performance_hint()` instead of `warning()` for `boundscheck()`
  Cython/Compiler/ExprNodes.py
  tests/memoryview/memoryview.pyx
Labels: Error Reporting
