Repository cython/cython, pull requests merged in 2023-04, with the labels that each got.

#5350 Refactor label interception code in for-loop and exception handling nodes to reduce redundancy
  Cython/Compiler/Code.py
  Cython/Compiler/Nodes.py
Labels: cleanup

#5352 Clean up the for-loop iterator before entering the 'else' branch
  Cython/Compiler/Nodes.py
Labels: Code Generation, cleanup

#5355 Fix AnnotationWriter for IndexNode with empty TupleNode
  Cython/CodeWriter.py
  tests/run/embedsignatures.pyx
Labels: defect, Code Generation

#5353 Implement support for the new PyLong struct layout in Py3.12a7
  Cython/Utility/Builtins.c
  Cython/Utility/Optimize.c
  Cython/Utility/StringTools.c
  Cython/Utility/TypeConversion.c
Labels: enhancement, Optimization, Code Generation

#5358 Fix duplication of `IS_UNSIGNED_IMPL`
  Cython/Utility/Buffer.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/Overflow.c
  tests/pypy2_bugs.txt
  tests/run/buffer_n_overflowcheck_T5356.pyx
Labels: defect, Code Generation

#5370 Backport .readthedocs.yaml
  .readthedocs.yaml
Labels: Documentation

#5368 Handle additions to signatures in Py3.12 dataclasses
  Cython/Compiler/Dataclass.py
  Cython/Utility/Dataclasses.c
  Cython/Utility/Dataclasses.py
Labels: defect, Python Semantics, Code Generation

#5357 Fix issues with partially optimized cascaded comparisons
  Cython/Compiler/ExprNodes.py
  tests/run/cascmp.pyx
Labels: defect, Code Generation

#5383 Distinguish api import functions from cython versions
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Utility/ImportExport.c
Labels: defect, Code Generation, P: blocker

#5375 Make memoryviews with aliased types comformable
  Cython/Compiler/PyrexTypes.py
  tests/memoryview/memoryview.pyx
Labels: defect, Type Analysis

#5390 Distinguish 'api' import functions from different Cython versions
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Utility/ImportExport.c
Labels: defect, Code Generation

#5395 Fix regression in code generation order for cdef classes
  Cython/Compiler/ModuleNode.py
  tests/run/cdef_class_order.pyx
Labels: Code Generation

#5213 Avoid Python int object creation when multiplying sequences with integers
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Utility/ObjectHandling.c
  tests/run/seq_mul.py
  tests/run/unicodemethods.pyx
Labels: Optimization

#5334 Add an example of a custom exception handler.
  docs/src/userguide/wrapping_CPlusPlus.rst
Labels: Documentation

#5408 prepare cython for PyPy3.10
  Cython/Compiler/TypeSlots.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
Labels: Code Generation, PyPy

#5406 Catch ValueError when calling memoryview()
  Cython/Compiler/FusedNode.py
  tests/memoryview/numpy_memoryview.pyx
Labels: defect, Code Generation
