Repository cython/cython, pull requests merged in 2023-01, with the labels that each got.

#5023 mark extension types as immutable
  Cython/Utility/ExtensionTypes.c
  tests/run/cclass_assign_attr_GH3100.pyx
Labels: defect, Code Generation

#5188 [0.29.x] Avoid using asyncio.get_event_loop
  tests/run/asyncio_generators.srctree
  tests/run/py35_asyncio_async_def.srctree
Labels: Testing

#5076 [0.29.x] Add support of const fused type memory views (GH-3118)
  Cython/Compiler/PyrexTypes.py
  tests/errors/fused_types.pyx
  tests/memoryview/numpy_memoryview_readonly.pyx
  tests/run/fused_types.pyx
Labels: defect, Cython Language Feature

#5196 Add `annotation_typing` in shadow.py
  Cython/Shadow.py
  tests/run/pure_py3.py
Labels: defect, Pure Python Mode

#5034 Fix the step for uploading platform-specific wheels to GitHub
  .github/workflows/wheels.yml
Labels: Build System

#5124 Make cpdef enums pickleable
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/CpdefEnums.pyx
  tests/run/cpdef_enums.pyx
  tests/run/cpdef_scoped_enums.pyx
Labels: enhancement, Python Semantics, Cython Language Feature

#5201 Initialize array fields of struct with memcpy
  Cython/Compiler/ExprNodes.py
  tests/run/struct_conversion.pyx
Labels: defect, Code Generation

#5205 Use Development release segment in public version identifiers
  Cython/Shadow.py
Labels: enhancement, Build System

#5209 Enhance `build_hex_version`
  Cython/Utils.py
Labels: cleanup

#4877 Improve cpdef enum to Python conversion
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/UtilityCode.py
  Cython/Utility/CpdefEnums.pyx
  tests/run/cpdef_enums.pyx
  tests/run/cpdef_enums_import.srctree
  tests/run/cpdef_scoped_enums.pyx
  tests/run/cpp_stl_conversion.pyx
Labels: enhancement, Cython Language Feature

#5210 Replace deprecated functions
  Cython/Utility/Embed.c
Labels: enhancement, Code Generation

#5073 Optimize dispatch for fused memoryview types
  Cython/Compiler/Builtin.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/Optimize.py
  Cython/Utility/Builtins.c
  tests/run/builtin_memory_view.pyx
Labels: enhancement, Code Generation

#5049 Use PyxCodeWriter in the dataclass TemplateCode
  Cython/Compiler/Code.py
  Cython/Compiler/Dataclass.py
  Cython/StringIOTree.pxd
  Cython/StringIOTree.py
Labels: cleanup

#5211 Disable parsing command line arguments
  Cython/Utility/Embed.c
Labels: defect, Code Generation

#5219 Fix bound class methods when unpacking builtin method calls
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  tests/run/bytearraymethods.pyx
  tests/run/bytesmethods.pyx
  tests/run/dict.pyx
Labels: defect, Optimization

#5217 Make sure we parse int(Py_UCS4) as a digit and not a plain character value integer
  Cython/Compiler/Optimize.py
  Cython/Utility/Builtins.c
  tests/run/py_ucs4_type.pyx
Labels: defect, Optimization

#5236 Avoid C++ warnings when initializing module state
  Cython/Compiler/ModuleNode.py
Labels: C++, defect, Code Generation
