Repository cython/cython, pull requests merged in 2023-02, with the labels that each got.

#5244 Declare support for Python 3.11
  setup.py
Labels: Build System

#5184 [docs] Parallelization tutorial
  docs/examples/tutorial/parallelization/manual_work.py
  docs/examples/tutorial/parallelization/manual_work.pyx
  docs/examples/tutorial/parallelization/median.py
  docs/examples/tutorial/parallelization/median.pyx
  docs/examples/tutorial/parallelization/norm.py
  docs/examples/tutorial/parallelization/norm.pyx
  docs/examples/tutorial/parallelization/normalize.py
  docs/examples/tutorial/parallelization/normalize.pyx
  docs/examples/tutorial/parallelization/parallel_sin.py
  docs/examples/tutorial/parallelization/parallel_sin.pyx
  docs/examples/tutorial/parallelization/setup.py
  docs/src/tutorial/index.rst
  docs/src/tutorial/parallelization.rst
Labels: Documentation

#5248 Softdeprecated C style array declaration in favour of Java style declaration
  docs/examples/tutorial/cython_tutorial/primes.pyx
  docs/examples/userguide/buffer/matrix_with_buffer.pyx
  docs/examples/userguide/language_basics/compile_time.pyx
  docs/examples/userguide/memoryviews/quickstart.pyx
  docs/src/tutorial/htmlreport_py.png
  docs/src/tutorial/htmlreport_pyx.png
  docs/src/userguide/language_basics.rst
Labels: cleanup, Documentation

#5254 Add .readthedocs.yaml
  .readthedocs.yaml
Labels: Documentation, Tools

#5234 Infer float in "safe" mode
  Cython/Compiler/TypeInference.py
  tests/run/pep526_variable_annotations.py
  tests/run/type_inference.pyx
Labels: Type Analysis

#4994 Fix an initialization reference counting error in the limited API
  Cython/Compiler/ModuleNode.py
Labels: defect, Code Generation

#4899 Fix bug with unused keyword arguments and locals
  Cython/Compiler/Nodes.py
  tests/run/locals.pyx
Labels: defect, Python Semantics

#5257 add missing exception C-APIs
  Cython/Includes/cpython/exc.pxd
Labels: enhancement, Library

#5079 Show warning when annotation type is unknown
  Cython/Compiler/ExprNodes.py
  docs/examples/userguide/buffer/matrix.py
  tests/errors/dataclass_e5.pyx
  tests/errors/pure_warnings.py
Labels: defect, Error Reporting

#4803 Auto-generation of Numpy ufuncs
  Cython/Compiler/Options.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/UFuncs.py
  Cython/Compiler/UtilNodes.py
  Cython/Tempita/_tempita.py
  Cython/Utility/NumpyImportArray.c
  Cython/Utility/UFuncs.pyx
  Cython/Utility/UFuncs_C.c
  docs/src/tutorial/memory_allocation.rst
  docs/src/userguide/external_C_code.rst
  docs/src/userguide/glossary.rst
  docs/src/userguide/index.rst
  docs/src/userguide/numpy_ufuncs.rst
  docs/src/userguide/parallelism.rst
  tests/run/ufunc.pyx
Labels: feature, Cython Language Feature, numpy

#5264 Fix limited API unicode iteration
  Cython/Utility/Optimize.c
Labels: defect, Code Generation

#5266 Add a missing pointer cast to limited api
  Cython/Utility/ExtensionTypes.c
Labels: defect, Code Generation

#5265 Fix cleanup of non-py-object constants on module close
  Cython/Compiler/Code.py
Labels: defect, Code Generation

#5279 fix depfile generation on Windows, across different drives
  Cython/Utils.py
Labels: defect, Build System
