Repository cython/cython, pull requests merged in 2023-03, with the labels that each got.

#5271 Fix a couple of memoryview issues
  Cython/Compiler/Builtin.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/Builtins.c
  tests/run/builtin_memory_view.pyx
Labels: defect, Code Generation

#5283 [0.29] fix depfile generation on Windows, across different drives
  Cython/Utils.py
Labels: defect, Build System

#5282 Order merged_in utility code
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Pipeline.py
  tests/run/cpdef_enums.pyx
Labels: defect, Code Generation

#5272 Fix annotation typing of Optional[tuple]
  Cython/Compiler/PyrexTypes.py
  tests/run/pep526_variable_annotations.py
Labels: defect, Type Analysis

#5281 Doc: Migrate Numpy ufunc to pure python
  docs/examples/userguide/numpy_ufuncs/ufunc.py
  docs/examples/userguide/numpy_ufuncs/ufunc.pyx
  docs/examples/userguide/numpy_ufuncs/ufunc_ctuple.py
  docs/examples/userguide/numpy_ufuncs/ufunc_ctuple.pyx
  docs/examples/userguide/numpy_ufuncs/ufunc_fused.py
  docs/examples/userguide/numpy_ufuncs/ufunc_fused.pyx
  docs/src/userguide/numpy_ufuncs.rst
Labels: Documentation

#5294 Allow 3.12-dev in limited-api to fail
  .github/workflows/ci.yml
Labels: defect, Testing

#5229 Allow nested C++ names after a module name
  Cython/Compiler/Nodes.py
  tests/run/cpp_nested_classes.pyx
  tests/run/cpp_nested_names.pxd
  tests/run/cpp_nested_names_helper.h
Labels: C++, enhancement

#5255 Renovate `docs/README`
  docs/README
  docs/README.md
Labels: cleanup

#5262 Add libcpp.cmath
  Cython/Includes/libcpp/cmath.pxd
  runtests.py
  tests/macos_cpp_bugs.txt
  tests/run/cpp_stl_cmath_cpp17.pyx
  tests/run/cpp_stl_cmath_cpp20.pyx
Labels: C++, Library

#5317 Try to fix FakeReference on c++03
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation

#5314 Add support for C++ std::any
  Cython/Includes/libcpp/any.pxd
  tests/run/cpp_stl_any.pyx
Labels: C++, enhancement, Library

#5318 Fix missing exported C function declarations with cimport_from_pyx enabled
  Cython/Compiler/FusedNode.py
  Cython/Compiler/ModuleNode.py
  tests/run/cimport_from_pyx.srctree
Labels: defect, Code Generation

#5325 Fix exception handling in memoryview utilitycode
  Cython/Utility/MemoryView.pyx
  tests/compile/fused_redeclare_T3111.pyx
  tests/errors/pure_warnings.py
  tests/memoryview/memoryview_no_withgil_check.pyx
Labels: performance, defect, Code Generation

#5302 allow IS_UNSIGNED to handle const types
  Cython/Compiler/Buffer.py
  Cython/Utility/Buffer.c
  Cython/Utility/Overflow.c
Labels: defect, Code Generation

#5330 [0.29.x] Use a more correct and specific CPython internals guard in __Pyx_Raise()
  Cython/Utility/Exceptions.c
Labels: defect, Code Generation

#5332 Fix ufunc GIL handling
  Cython/Compiler/UFuncs.py
  Cython/Utility/UFuncs.pyx
  tests/run/ufunc.pyx
Labels: defect, Code Generation

#5298 Restore 0.29.x handling of None fused memoryviews
  Cython/Compiler/FusedNode.py
  tests/run/fused_types.pyx
Labels: defect, Cython Language Feature

#5320 Add a test for relative cimport within a submodule
  tests/run/relative_cimport.srctree
Labels: Testing

#5310 Added documentation about the GIL
  docs/src/quickstart/cythonize.rst
  docs/src/tutorial/pure.rst
  docs/src/userguide/index.rst
  docs/src/userguide/nogil.rst
Labels: Documentation

#5309 Add C++20 mathematical constants
  Cython/Includes/libcpp/numbers.pxd
  tests/run/cpp_stl_numbers.pyx
Labels: C++, Library

#5291 Do not attempt to write out a depfile on failure
  Cython/Compiler/Main.py
Labels: defect, Build System

#5289 [0.29] Account for possible extension type struct padding when calculating the itemsize for the "size changed" check
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ImportExport.c
Labels: defect, Error Reporting

#5287 Allow soft-complex->double coercion to run without gil
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/UtilNodes.py
  Cython/Utility/Complex.c
  tests/run/cpow.pyx
Labels: defect, Code Generation, P: blocker

#5336 Allow InterpretCompilerDirectives.visit_AnnotationNode to process nodes having no children
  Cython/Compiler/ParseTreeTransforms.py
  tests/run/annotation_typing.pyx
Labels: defect, Type Analysis

#5295 Improve error message for 'cimport cython.floating'
  Cython/Compiler/ParseTreeTransforms.py
  tests/errors/e_invalid_special_cython_modules.py
Labels: enhancement, Error Reporting

#5339 Fix compilation with CPython 3.12a6
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation

#5307 Backport CYTHON_FORCE_REGEN=1 feature to 0.29
  Cython/Build/Dependencies.py
Labels: enhancement, Build System

#5343 Avoid deprecated Py_OptimizeFlag in Py3.12
  Cython/Compiler/Builtin.py
  Cython/Compiler/Nodes.py
  Cython/Utility/Exceptions.c
  Cython/Utility/ModuleSetupCode.c
Labels: defect, Code Generation
