Repository cython/cython, pull requests merged in 2023-06, with the labels that each got.

#5374 Move FAQ from wiki to userguide
  docs/src/tutorial/strings.rst
  docs/src/userguide/faq.rst
  docs/src/userguide/migrating_to_cy30.rst
Labels: Documentation

#5459 use pypy-3.9-v7.3.12rc2 instead of a nightly
  .github/workflows/ci.yml
Labels: cleanup, PyPy

#5466 Update numpy tutorial not to use deprecated/removed np.int
  docs/examples/tutorial/numpy/convolve2.pyx
  docs/src/tutorial/numpy.rst
  docs/src/userguide/memoryviews.rst
Labels: Documentation

#5483 Don't remove const for reverse iteration
  Cython/Compiler/ExprNodes.py
  Cython/Includes/libcpp/map.pxd
  tests/run/cpp_iterators.pyx
Labels: C++, defect, Code Generation

#5485 added include_dirs to numpy pythran docs
  docs/src/userguide/numpy_pythran.rst
Labels: Documentation, Pythran

#5490 Update pypy in CI to released version
  .github/workflows/ci.yml
Labels: Build System, cleanup

#5487 Dont override language_level from directives when set to None
  Cython/Compiler/Options.py
  tests/build/cython_language_level.srctree
Labels: defect

#5496 Correct links in faq
  docs/src/userguide/faq.rst
Labels: Documentation

#5410 Fix to-py conversion with duplicate enum values
  Cython/Compiler/Nodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  tests/run/cpdef_enums.pyx
Labels: defect, Code Generation

#5501 Temporary fix for tests on Python <= 3.5
  tests/run/cpdef_enums.pyx
Labels: defect, Testing

#5505 print --version to stdout [no ci]
  Cython/Compiler/Main.py
Labels: defect, Error Reporting

#5503 Fix display error on Cython3.0 document on troubleshooting
  docs/src/tutorial/embedding.rst
  docs/src/userguide/troubleshooting.rst
Labels: Documentation
