Repository cython/cython, pull requests merged in 2023-08, with the labels that each got.

#5582 Run CI with PyPy3, update caching
  .github/workflows/ci.yml
Labels: defect, Testing

#5594 Allow PyPy users to define use_type_specs
  Cython/Utility/ModuleSetupCode.c
Labels: PyPy

#5606 Avoid using Py_OptimizeFlag in the Limited API.
  Cython/Utility/Exceptions.c
Labels: defect, Code Generation, limited api

#5613 Fix example in extension_types.rst
  docs/src/userguide/extension_types.rst
Labels: Pure Python Mode, Documentation

#5614 Fix fused function default argument coercion
  Cython/Compiler/ExprNodes.py
  tests/run/fused_def.pyx
Labels: defect, Code Generation

#5550 Get some of the limited API working with Py_LIMITED_API defined
  Cython/Compiler/Nodes.py
  Cython/Utility/CythonFunction.c
  Cython/Utility/Exceptions.c
  Cython/Utility/FunctionArguments.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/TypeConversion.c
  runtests.py
  tests/run/isolated_limited_api_tests.srctree
Labels: limited api

#5597 Use hex to store large integers
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  Cython/Utils.py
  tests/run/constant_folding.py
  tests/run/int_literals.pyx
  tests/run/large_integer_T5290.py
  tests/run/pure_py.py
Labels: enhancement, Code Generation

#5608 codespell: add config, workflow (so no new typos sneak in) and get some typos fixed
  .codespellrc
  .github/workflows/codespell.yml
  CHANGES.rst
  Cython/Compiler/PyrexTypes.py
  Cython/Tempita/_tempita.py
  Tools/cython-numpy-mode-kate.xml
  Tools/gen_tests_for_posix_pxds.py
  Tools/kate.diff
  runtests.py
  tests/run/cpp_classes_def.pyx
  tests/run/pep448_test_extcall.pyx
Labels: cleanup, Testing

#5621 Fix minor regression related to print_version()
  Cython/Compiler/Main.py
Labels: Build System

#5620 refactor out use of numpy.distutils
  Demos/setup.py
  Tools/ci-run.sh
  runtests.py
  test-requirements-312.txt
  test-requirements-36.txt
Labels: cleanup

#5631 Allow interdependency between cpdef enums
  Cython/Compiler/Nodes.py
  tests/compile/cppenum.pyx
Labels: C++, defect, Code Generation

#5632 Avoid conflict between int-to-py and anonymous-enum-to-py
  Cython/Compiler/PyrexTypes.py
  tests/run/c_int_types_T255.pyx
Labels: defect, Code Generation

#5574 Fix reference counting of memoryview arguments to special functions
  Cython/Compiler/Nodes.py
  tests/memoryview/memoryview.pyx
Labels: defect, Code Generation

#5593 Use NULL as default exception value for ptrs
  Cython/Compiler/PyrexTypes.py
  tests/run/exceptionpropagation.pyx
Labels: cleanup, Type Analysis

#5538 Fix leaking of Relative cimport out of the package to the environment
  Cython/Compiler/Main.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/TreeFragment.py
  Cython/Compiler/UtilityCode.py
  tests/run/relative_import_leak.srctree
Labels: defect, Build System

#5537 Fix attribute lookup of standard library names
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  tests/run/pep526_variable_annotations.py
Labels: defect, Type Analysis

#5622 Add support of `typing.Optional` to memoryviews
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  tests/errors/e_typing_errors.pyx
  tests/errors/e_typing_optional.py
  tests/memoryview/memoryview_annotation_typing.py
Labels: Pure Python Mode

#5603 Switch __pyx_buffmt_parse_array to return an int
  Cython/Utility/Buffer.c
Labels: cleanup

#5617 Get some minimal cdef classes working with `Py_LIMITED_API`
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Optimize.py
  Cython/Utility/CythonFunction.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/FunctionArguments.c
  Cython/Utility/ModuleSetupCode.c
  tests/run/isolated_limited_api_tests.srctree
Labels: Code Generation, limited api

#5647 Remove useless shebang
  Cython/Build/Cythonize.py
Labels: defect, Build System

#5653 Fix invalid C code when assigning int->fused complex with CYTHON_CCOMPLEX=0
  Cython/Compiler/FusedNode.py
  tests/run/fused_types.pyx
  tests/run/fused_types_complex.pyx
Labels: defect, Code Generation

#5652 Avoid useless runtime type checks when coercing a None default argument to a Python type argument.
  Cython/Compiler/ExprNodes.py
  tests/run/default_optional_gh5643.py
Labels: defect, Type Analysis

#5655 Fix loop var declaration
  Cython/Compiler/Nodes.py
Labels: defect, Code Generation

#5656 Add enum class decl to before types block
  Cython/Utility/CppSupport.cpp
  tests/compile/cppenum.pyx
Labels: C++, defect, Code Generation

#5666 Fix typos in documentation
  docs/src/tutorial/embedding.rst
  docs/src/userguide/extension_types.rst
Labels: Documentation

#5640 Define thread_local for C++
  Cython/Utility/ModuleSetupCode.c
Labels: C++, Code Generation

#5667 Fix a null comparison compiler warning visible with gcc 12
  Cython/Utility/ImportExport.c
Labels: Code Generation
