Repository cython/cython, pull requests merged in 2024-11, with the labels that each got.

#6470 Pick a few small fixes out of #6226
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ParseTreeTransforms.py
Labels: defect, Type Analysis

#6481 Fix & on 0 produced by int.from_bytes on Python 3.10
  Cython/Utility/Optimize.c
  tests/run/pyintop.pyx
Labels: defect, Code Generation

#6378 Drop Python 3.7, require Python 3.8+
  .github/workflows/ci.yml
  Cython/Compiler/Main.py
  setup.py
Labels: cleanup

#6494 Fix Pythran
  Cython/Compiler/Pythran.py
  Tools/ci-run.sh
  tests/run/ufunc.pyx
Labels: Pythran

#6469 Turn off module state for Limited API
  Cython/Utility/ModuleSetupCode.c
  tests/run/isolated_limited_api_tests.srctree
Labels: limited api

#6483 Use setup-python for the free-threading CI job
  .github/workflows/ci.yml
  Tools/ci-run.sh
  setup.py
Labels: Testing

#6512 Remove old PyPy2 workaround
  Cython/Compiler/FusedNode.py
Labels: cleanup, PyPy

#6509 Skip limited API tests on freethreading build
  tests/run/isolated_limited_api_tests.srctree
  tests/run/subinterpreters.srctree
  tests/run/subinterpreters_threading_stress_test.srctree
Labels: Testing

#6517 Document CYTHON_CCOMPLEX
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#6507 Make access fused access to ndarray thread safe
  Cython/Utility/ImportExport.c
Labels: defect, Code Generation, nogil CPython

#6508 Fix an issue with fused dispatch on freethreading
  Cython/Compiler/FusedNode.py
  tests/run/fused_def.pyx
Labels: defect, Code Generation, nogil CPython

#6510 Move PyUnstable_Module_SetGIL out of "if MODULE_STATE"
  Cython/Compiler/ModuleNode.py
Labels: defect, Code Generation, nogil CPython

#6516 Implement cython.critical_section
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Options.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/PyrexTypes.py
  Cython/Shadow.py
  Cython/Utility/ModuleSetupCode.c
  docs/src/userguide/freethreading.rst
  docs/src/userguide/source_files_and_compilation.rst
  tests/errors/critical_sections.pyx
  tests/run/critical_sections.pyx
Labels: feature, Cython Language Feature, nogil CPython

#6522 Disable some parallel tests in freethreading Python
  tests/run/sequential_parallel.pyx
Labels: Testing, nogil CPython
