Repository cython/cython, pull requests merged in 2024-07, with the labels that each got.

#6283 Clean up "c_string_type" and "c_string_encoding" for Py3
  Cython/Build/Tests/TestCythonizeArgsParser.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Options.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/CppConvert.pyx
  Cython/Utility/TypeConversion.c
  docs/examples/tutorial/string/auto_conversion_2.pyx
  docs/examples/tutorial/string/auto_conversion_3.pyx
  docs/src/tutorial/strings.rst
Labels: cleanup

#6260 Compile Cython in the limited API
  .github/workflows/ci.yml
  Tools/ci-run.sh
  setup.py
Labels: Build System, Testing, limited api

#6234 Add sanity check on import for ABI details
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ModuleSetupCode.c
  tests/run/abitests.srctree
Labels: nogil CPython

#6171 [3.0.x] Fix type of str call
  Cython/Compiler/Optimize.py
  tests/run/cython3.pyx
  tests/run/unicodemethods.pyx
Labels: defect, Type Analysis

#6243 Add option to silence IF deprecation warning
  Cython/Compiler/Options.py
  Cython/Compiler/Parsing.py
  docs/src/userguide/source_files_and_compilation.rst
Labels: Error Reporting

#6086 Make fused ctuples work
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/PyrexTypes.py
  tests/run/ufunc.pyx
Labels: defect

#6242 Add freethreading_compatible directive to set Py_mod_gil slot
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Options.py
  docs/src/userguide/source_files_and_compilation.rst
  tests/run/freethreading_compatible.srctree
Labels: nogil CPython

#6292 Discard in-tests against empty sequences if they have no side effects.
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  tests/run/inop.pyx
  tests/run/tuple.pyx
Labels: Optimization

#6296 Simply macros to enable Limited API mode
  Cython/Utility/ModuleSetupCode.c
  docs/src/userguide/source_files_and_compilation.rst
  setup.py
  tests/run/isolated_limited_api_tests.srctree
Labels: limited api

#5889 Visit type in traverse (heap types)
  Cython/Compiler/ModuleNode.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/ExtensionTypes.c
Labels: defect, Code Generation

#6196 Handle typedefs in ufuncs
  Cython/Compiler/UFuncs.py
  Cython/Utility/UFuncs.pyx
  Cython/Utility/UFuncs_C.c
  tests/run/ufunc.pyx
Labels: Cython Language Feature

#6169 string/iter/shutdown limited API fixes
  Cython/Compiler/ModuleNode.py
  Cython/Utility/Complex.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/StringTools.c
  Cython/Utils.py
Labels: limited api

#6300 Remove CYTHON_USE_ASYNC_SLOTS
  Cython/Compiler/TypeSlots.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/ModuleSetupCode.c
  docs/src/userguide/source_files_and_compilation.rst
Labels: cleanup

#6298 Freethreading documentation
  docs/src/userguide/freethreading.rst
  docs/src/userguide/index.rst
  docs/src/userguide/nogil.rst
Labels: Documentation, nogil CPython

#6297 Document Limited API support
  docs/src/userguide/index.rst
  docs/src/userguide/limited_api.rst
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation, limited api

#6309 Remove Py2 only __cmp__
  Cython/Compiler/PyrexTypes.py
Labels: cleanup

#6311 Avoid reassigning child_attrs
  Cython/Compiler/TypeInference.py
Labels: cleanup

#6308 Try to add GraalPython to CI
  .github/workflows/ci.yml
  Tools/ci-run.sh
  runtests.py
  tests/graal_bugs.txt
Labels: Testing

#6281 Limited API call speed improvments
  Cython/Compiler/Nodes.py
  Cython/Utility/CythonFunction.c
  Cython/Utility/ObjectHandling.c
  tests/errors/w_cdef_override.pyx
  tests/run/pstats_profile_test.pyx
Labels: limited api

#6293 Unset PYTHON_GIL env variable in freethreading_compatible tests
  runtests.py
  tests/run/freethreading_compatible.srctree
Labels: Testing

#4878 [Docs] Fix sphinx build warnings, improve C expressions
  docs/src/tutorial/clibraries.rst
  docs/src/tutorial/strings.rst
  docs/src/userguide/external_C_code.rst
  docs/src/userguide/language_basics.rst
  docs/src/userguide/pypy.rst
  docs/src/userguide/wrapping_CPlusPlus.rst
Labels: cleanup, Documentation
