Repository cython/cython, pull requests merged in 2024-01, with the labels that each got.

#5938 Add another "types in Shadow.py" test
  Cython/Compiler/PyrexTypes.py
  Cython/Shadow.py
  Cython/Tests/TestShadow.py
Labels: Testing

#5940 Fix types in cpdef_extern_func
  tests/run/cpdef_extern_func.pyx
Labels: Testing

#5804 Use vectorcall by default
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/TypeConversion.c
  tests/run/call_py_cy.pyx
Labels: enhancement, Code Generation

#5945 Force closing gzip file in TestCyCache
  Cython/Build/Tests/TestCyCache.py
Labels: Testing

#5947 Try disabling gc for line-trace tests
  tests/run/line_trace.pyx
Labels: Testing

#5946 Update doc requirements and pin them to recent versions
  CHANGES.rst
  doc-requirements.txt
Labels: Documentation

#5916 Improve message when exception values don't match
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  tests/errors/cfuncptr.pyx
  tests/errors/e_excvalfunctype.pyx
Labels: Error Reporting

#5962 Improve message when exception values don't match (3.0.x backport)
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  tests/errors/cfuncptr.pyx
  tests/errors/e_excvalfunctype.pyx
Labels: Error Reporting

#5842 Drop Numpy includes
  Cython/Includes/numpy/__init__.pxd
Labels: cleanup, Library, numpy

#5966 Fix distutils sources syntax
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation
