Repository cython/cython, pull requests merged in 2024-05, with the labels that each got.

#6175 Warn on use of the old Py2 buffer protocol
  Cython/Compiler/Code.py
  Cython/Compiler/ParseTreeTransforms.py
  docs/src/userguide/special_methods.rst
Labels: Error Reporting

#6168 Fix bytes startswith/endswith with nonbytes argument
  Cython/Utility/StringTools.c
  tests/run/bytesmethods.pyx
Labels: defect, Code Generation

#6177 [Docs] Document examples of arrays of pointers and pointer to array
  docs/src/userguide/language_basics.rst
Labels: Documentation

#5997 Use the new large PyLong conversion functions in Py3.13.
  Cython/Utility/TypeConversion.c
Labels: enhancement, Code Generation

#6073 Accelerate divmod() in Cython by calling C div() for C int type integers
  Cython/Compiler/Builtin.py
  Cython/Utility/Builtins.c
  tests/run/builtin_divmod.py
Labels: performance

#4866 Improve `@dataclass` example
  docs/examples/userguide/extension_types/dataclass.pyx
Labels: Documentation

#6179 Call `__set_name__` during setting type attribute.
  Cython/Utility/ExtensionTypes.c
  docs/src/userguide/special_methods.rst
  tests/run/module_init_error.srctree
  tests/run/special_methods_T561.pyx
Labels: Python Semantics

#6182 Test runner: Python 3.13 removes unittest.findTestCase
  runtests.py
Labels: Testing

#6190 Mark `libcpp.optional.optional.value()` as `except +`
  Cython/Includes/libcpp/optional.pxd
  tests/run/cpp_stl_optional.pyx
Labels: C++, Library

#6188 remove unused include pycore_frame
  Cython/Utility/ObjectHandling.c
Labels: cleanup

#6181 Documentation of old buffer syntax options
  docs/src/tutorial/numpy.rst
Labels: Documentation

#6180 Update documentation refcounting example
  docs/examples/userguide/language_basics/parameter_refcount.py
  docs/examples/userguide/language_basics/parameter_refcount.pyx
  docs/src/userguide/language_basics.rst
Labels: Documentation

#6187 Py3.13 support in cpython/time.pxd
  Cython/Includes/cpython/time.pxd
  tests/run/time_pxd.pyx
Labels: defect, Library

#5800 Make classmethod work in limited-api
  Cython/Utility/CythonFunction.c
  tests/run/isolated_limited_api_tests.srctree
Labels: limited api

#6167 Categorise memoryview tests
  runtests.py
  tests/limited_api_bugs.txt
  tests/memoryview_tests.txt
Labels: Testing, limited api

#6089 Fix write unraisable followed by interpretter shutdown
  Cython/Utility/Exceptions.c
  tests/run/dealloc_raise.srctree
Labels: defect, Code Generation

#6204 Fix crash when function contains fused extension type
  Cython/Compiler/PyrexTypes.py
  tests/errors/fused_types.pyx
Labels: defect

#6199 Try to improve parallel in free-threading
  Cython/Compiler/Code.py
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Runtime/refnanny.pyx
  Cython/Utility/ModuleSetupCode.c
Labels: nogil CPython

#6213 Rename to "CYTHON_COMPILING_IN_CPYTHON_FREETHREADING"
  Cython/Compiler/Code.py
  Cython/Compiler/Nodes.py
  Cython/Runtime/refnanny.pyx
  Cython/Utility/ModuleSetupCode.c
  tests/compile/buildenv.pyx
Labels: cleanup, nogil CPython

#6209 [3.0.X] Fix crash when function contains fused extension type
  Cython/Compiler/PyrexTypes.py
  tests/errors/fused_types.pyx
Labels: defect
