Repository cython/cython, pull requests merged in 2024-12, with the labels that each got.

#6538 Add PyWeakref_GetRef to cpython.weakref
  Cython/Includes/cpython/weakref.pxd
Labels: Library

#6537 When tracing C return values, allow the Python coercion to fail
  Cython/Compiler/Code.py
  Cython/Utility/Profile.c
  tests/run/sys_monitoring.py
Labels: defect, Code Generation, Coverage

#6511 Change calculation of "unreachable" for double dealloc
  tests/run/double_dealloc_T796.pyx
Labels: Testing

#6549 Remove unnecessary allow_failures
  .github/workflows/ci.yml
Labels: Testing, limited api, nogil CPython

#6544 Improve limited API name formatting...
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Utility/Builtins.c
  Cython/Utility/Coroutine.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/FunctionArguments.c
  Cython/Utility/ImportExport.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Optimize.c
  Cython/Utility/TypeConversion.c
Labels: Python Semantics, limited api

#6543 Enable a bunch of Limited API tests
  .github/workflows/ci.yml
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  Cython/Utility/Builtins.c
  Cython/Utility/Coroutine.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/TypeConversion.c
  runtests.py
  tests/limited_api_bugs.txt
  tests/memoryview_tests.txt
  tests/test_in_limited_api.txt
Labels: Testing, limited api

#6550 Correct RST markup @ `source_files_and_compilation` doc
  docs/conf.py
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#6563 Enable Limited API run tests (a-d)
  Cython/Utility/FunctionArguments.c
  Cython/Utility/Optimize.c
  tests/limited_api_bugs.txt
  tests/memoryview_tests.txt
  tests/run/builtin_basestring.pyx
Labels: Testing, limited api

#6564 Enable Limited API run tests (e-o)
  Cython/Utility/ObjectHandling.c
  tests/limited_api_bugs.txt
  tests/memoryview_tests.txt
  tests/run/exectest.pyx
Labels: Testing, limited api

#6567 Enable remaining Limited API run tests
  Cython/Utility/ObjectHandling.c
  tests/limited_api_bugs.txt
  tests/memoryview_tests.txt
Labels: Testing, limited api

#6568 Make calling inherited slots work in the limited API
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/TypeSlots.py
  Cython/Utility/ModuleSetupCode.c
  tests/limited_api_bugs.txt
Labels: Code Generation, cleanup, limited api

#6566 Fix `IndexError` when stepping the debugger through unindexed C code
  Cython/Debugger/libcython.py
Labels: Tools

#6573 Fix lookup of builtins in Limited API
  Cython/Utility/ObjectHandling.c
  tests/limited_api_bugs.txt
Labels: defect, Code Generation, limited api

#6574 Switch refnanny to PyMutex on freethreading
  Cython/Runtime/refnanny.pyx
Labels: cleanup, freethreading CPython

#6580 Fix iteration over cpp input ranges
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
Labels: C++, Code Generation

#6584 Test requirements jupyter->ipython
  test-requirements-cpython.txt
Labels: Testing
