Repository cython/cython, pull requests merged in 2024-09, with the labels that each got.

#6374 Remove Py2 'str' type
  Cython/Build/Tests/TestCythonizeArgsParser.py
  Cython/CodeWriter.py
  Cython/Compiler/AnalysedTreeTransforms.py
  Cython/Compiler/AutoDocTransforms.py
  Cython/Compiler/Builtin.py
  Cython/Compiler/Code.pxd
  Cython/Compiler/Code.py
  Cython/Compiler/Dataclass.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/Interpreter.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/Options.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Scanning.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/Visitor.py
  Cython/Includes/cpython/object.pxd
  Cython/Shadow.py
  Cython/Tempita/_looper.py
  Cython/Tempita/_tempita.py
  Cython/Utility/Builtins.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Optimize.c
  Cython/Utility/StringTools.c
  tests/errors/e_strcoerce.pyx
  tests/errors/string_assignments.pyx
  tests/run/builtin_basestring.pyx
  tests/run/constant_folding_cy.pyx
  tests/run/cpp_stl_string.pyx
  tests/run/cstringmul.pyx
  tests/run/embedsignatures.pyx
  tests/run/strmethods.pyx
  tests/run/tuple_constants.pyx
  tests/run/type_inference.pyx
  tests/run/unicode_ascii_auto_encoding.pyx
  tests/run/unicodemethods.pyx
Labels: cleanup, Type Analysis

#6377 Allow update_cpp_extension to specifiy a higher standard
  runtests.py
Labels: Testing

#6380 Adds default to Compiler directives docs
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#6383 Optimise constant f-strings and constant builtin method calls
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/Tests/TestBuiltin.py
  tests/run/constant_folding.py
  tests/run/fstring.pyx
Labels: Optimization

#6120 Fix missing flow control for assignment expression
  Cython/Compiler/FlowControl.py
  tests/run/extra_walrus.py
Labels: defect, Code Generation

#6386 Consistent funcstate for slot function generation
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
Labels: Code Generation, cleanup

#5323 Modulestate refactor
  Cython/Compiler/Code.pxd
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/TypeSlots.py
  Cython/Utility/Builtins.c
  Cython/Utility/Coroutine.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/Exceptions.c
  Cython/Utility/ImportExport.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Printing.c
  Cython/Utility/Profile.c
  Cython/Utility/TestCythonScope.pyx
  tests/compile/fused_redeclare_T3111.pyx
  tests/errors/pure_warnings.py
Labels: Code Generation, cleanup

#6333 Add support of `typing.Union[XYZ, None]`
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  tests/errors/e_typing_errors.pyx
  tests/memoryview/memoryview_annotation_typing.py
  tests/run/annotation_typing.pyx
  tests/run/ext_type_none_arg.pyx
  tests/run/pep526_variable_annotations.py
Labels: feature, Pure Python Mode

#6389 Document `Union[tp, None]`
  docs/src/tutorial/pure.rst
Labels: Documentation

#6375 Fix cpp_locals code generation with unused expressions
  Cython/Compiler/ParseTreeTransforms.py
Labels: C++, defect, Code Generation

#6376 Disallow cpp_locals and boolean binary operators
  Cython/Compiler/ExprNodes.py
  tests/run/cpp_operators.pyx
Labels: C++, defect, Code Generation

#6390 Implement optional annotation type `tp | None`
  Cython/Compiler/ExprNodes.py
  tests/errors/e_typing_errors.pyx
  tests/memoryview/memoryview_annotation_typing.py
  tests/run/annotation_typing.pyx
  tests/run/ext_type_none_arg.pyx
  tests/run/pep526_variable_annotations.py
  tests/run/pure_ctuple.py
  tests/run/pyintop.pyx
Labels: enhancement, Pure Python Mode

#6398 Support "cython.const[base_type]" and "cython.volatile[base_type]" in Python code
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Shadow.py
  Cython/Shadow.pyi
  Tools/cython-generate-lexicon.py
  Tools/cython-generate-shadow-pyi.py
  docs/src/tutorial/pure.rst
  runtests.py
  tests/run/pure_py.py
  tests/run/pure_py3.py
Labels: enhancement, Pure Python Mode

#6407 Fix inplace assignment on nested attributes without GIL
  Cython/Compiler/ParseTreeTransforms.py
  tests/compile/inplace_lhs_nested.pyx
Labels: defect, Code Generation
