Repository cython/cython, pull requests merged in 2024-06, with the labels that each got.

#5840 Support weakref in limited api cdef classes
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Utility/ModuleSetupCode.c
  tests/run/isolated_limited_api_tests.srctree
Labels: limited api

#5843 Get basic generators running in Limited API
  Cython/Utility/Coroutine.c
  Cython/Utility/ObjectHandling.c
  tests/run/isolated_limited_api_tests.srctree
Labels: limited api

#6230 Fix segfault on zero-length slice assignment on memoryview
  Cython/Utility/MemoryView.pyx
  tests/memoryview/memoryview.pyx
Labels: defect, Code Generation

#6229 Set up uploading non-compiled nightly wheels twice weekly
  .github/workflows/nightly-wheels.yml
Labels: Testing

#6233 Remove some more unused Py2 stuff
  Cython/Compiler/ModuleNode.py
  Cython/Utility/TypeConversion.c
Labels: cleanup

#6241 Pre-clean docstrings when running EmbedSignature transform
  Cython/Compiler/AutoDocTransforms.py
  tests/run/embedsignatures.pyx
Labels: Code Generation

#6246 Copy py_limited_api attribute of setuptools extension
  Cython/Build/Dependencies.py
  docs/src/userguide/source_files_and_compilation.rst
Labels: Build System, limited api

#6235 Always treat cppclasses in C++ mode
  Cython/Compiler/Main.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Symtab.py
  tests/errors/e_cpp_only_features.pyx
Labels: C++

#6135 [0.29.x] Fix Python 3.12 tests
  runtests.py
Labels: Testing

#6255 Improve reporting distutils LinkErrors
  runtests.py
Labels: Testing

#6237 Fix use of __Pyx_TEST_large_func_pointers
  Cython/Utility/ImportExport.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/TypeConversion.c
Labels: defect, Code Generation

#6267 Make modulestate optional in limited API
  Cython/Utility/ModuleSetupCode.c
Labels: limited api

#6266 malloc -> PyMem_Malloc in MergeVTables
  Cython/Utility/ImportExport.c
Labels: cleanup

#6262 Fix test_dataclasses for Python 3.13
  Tools/dataclass_test_data/test_dataclasses.py
  tests/run/test_dataclasses.pyx
Labels: Testing

#6163 Fix CPython and AVOID_BORROWED_REFS
  Cython/Utility/FunctionArguments.c
Labels: defect, Code Generation

#6273 Move more generated init code after user code
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/StringTools.c
Labels: Code Generation, cleanup

#6259 Enable vectorcall on limited api cyfunctions
  Cython/Utility/CythonFunction.c
  Cython/Utility/FunctionArguments.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
Labels: limited api

#6195 Fix PyInteger / float division
  Cython/Compiler/ExprNodes.py
  tests/run/type_inference.pyx
Labels: defect, Type Analysis

#6276 Fix module cleanup for global memoryview slices.
  Cython/Compiler/Code.py
Labels: defect, Code Generation

#6277 Avoid traversing constants with Py_VISIT()
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  Cython/Utility/CythonFunction.c
  Cython/Utility/ModuleSetupCode.c
  docs/src/userguide/source_files_and_compilation.rst
Labels: enhancement, Code Generation

#6278 Rename PyInt_* usages to PyLong_*
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/MemoryView_C.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Optimize.c
  Cython/Utility/StringTools.c
  Cython/Utility/TypeConversion.c
Labels: Code Generation, cleanup

#6269 Change hasattr to Python 3 behaviour
  Cython/Utility/Builtins.c
  tests/run/hasattr.py
Labels: Python3 Semantics
