Repository cython/cython, pull requests merged in 2024-03, with the labels that each got.

#6047 Mention `binding` in the size faq
  docs/src/userguide/faq.rst
Labels: Documentation

#6050 Add note about docstring to 'How do I reduce the size of the binary modules' faq
  docs/src/userguide/faq.rst
Labels: Documentation

#6031 Cleanup of SetItemInTypeDict
  Cython/Compiler/ExprNodes.py
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/ModuleSetupCode.c
Labels: Code Generation, cleanup

#6039 Disable GCC warnings/errors about wrong self casts in final function calls
  Cython/Compiler/ExprNodes.py
Labels: defect, Code Generation

#6057 Avoid "unused argument" warning on Py3.7
  Cython/Utility/ObjectHandling.c
Labels: cleanup

#6055 Reduce the overhead of creating the function code objects at module init time
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ModuleSetupCode.c
Labels: Code Generation, cleanup

#6054 Avoid unpacking method calls at class scope
  Cython/Compiler/Optimize.py
Labels: Code Generation, cleanup

#5710 Avoid using strings for exception_value of func_type
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/PyrexTypes.py
  tests/run/exceptionpropagation.pyx
  tests/run/pure_py.py
Labels: cleanup, Type Analysis

#6036 Rationalize the different cline traceback options
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Options.py
  Cython/Distutils/build_ext.py
  Cython/Utility/Exceptions.c
  docs/src/userguide/source_files_and_compilation.rst
  runtests.py
  tests/run/cline_in_traceback.srctree
Labels: cleanup, Cython Language Feature

#6065 Make UtilityCode.__eq__ account for "init" section
  Cython/Compiler/Code.py
  Cython/Compiler/Tests/TestUtilityLoad.py
Labels: defect, Code Generation

#6076 make tests run on numpy1.x and numpy2.x
  tests/memoryview/contig_check.pyx
  tests/memoryview/memoryview_annotation_typing.py
  tests/memoryview/numpy_memoryview.pyx
  tests/memoryview/numpy_memoryview_readonly.pyx
  tests/memoryview/relaxed_strides.pyx
  tests/run/numpy_parallel.pyx
  tests/run/numpy_test.pyx
  tests/run/ufunc.pyx
Labels: Testing, numpy

#6090 Move Cython cache to separate module
  Cython/Build/Cache.py
  Cython/Build/Cythonize.py
  Cython/Build/Dependencies.py
  Cython/Build/Inline.py
  Cython/Compiler/Options.py
  Cython/Utils.py
Labels: cleanup

#6040 C++ complex class fixes and tests
  Cython/Includes/libcpp/complex.pxd
  docs/examples/userguide/wrapping_CPlusPlus/python_to_cpp.pyx
  docs/src/userguide/troubleshooting.rst
  docs/src/userguide/wrapping_CPlusPlus.rst
  tests/run/complex_numbers_cpp.pyx
Labels: C++, Library

#6087 Fix warnings for "implicit noexcept" when using `legacy_implicit_noexcept=True`
  Cython/Compiler/Nodes.py
  Cython/Compiler/Parsing.py
  Cython/Includes/cpython/array.pxd
  Cython/Includes/cpython/complex.pxd
  Cython/Includes/cpython/datetime.pxd
  Cython/Includes/cpython/time.pxd
  tests/run/legacy_implicit_noexcept.pyx
Labels: Error Reporting

#6101 Change a "char *" to "const char*" in import code
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ImportExport.c
Labels: cleanup

#6105 3.0.x fix legacy_implicit_noexcept tests
  tests/run/legacy_implicit_noexcept.pyx
Labels: Testing

#6102 [3.0.x] Disable all freelist code outside CPython and add a new guard
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ModuleSetupCode.c
Labels: Code Generation

#3235 Cppclass overloadable methods
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Symtab.py
  tests/errors/cpp_no_constructor.pyx
  tests/run/cpp_classes_def.pyx
  tests/run/cpp_method_overloading.pyx
Labels: C++, Cython Language Feature

#6100 more fixes for NumPy2
  tests/run/numpy_pythran.pyx
  tests/run/numpy_pythran_unit.pyx
  tests/run/numpy_test.pyx
Labels: Testing, numpy

#6077 Reserve vector memory upfront
  Cython/Utility/CppConvert.pyx
  tests/run/cpp_stl_conversion.pyx
Labels: C++, performance, enhancement

#5907 Cleanup: use annotations instead of type overrides in pxd files
  Cython/Build/Dependencies.py
  Cython/Compiler/Code.pxd
  Cython/Compiler/Code.py
  Cython/Compiler/FlowControl.pxd
  Cython/Compiler/FlowControl.py
  Cython/Compiler/ParseTreeTransforms.pxd
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.pxd
  Cython/Compiler/Parsing.py
  Cython/Compiler/Scanning.pxd
  Cython/Compiler/Scanning.py
  Cython/Compiler/Tests/TestScanning.py
  Cython/Compiler/Visitor.py
  Cython/Plex/DFA.pxd
  Cython/Plex/DFA.py
  Cython/Plex/Machines.pxd
  Cython/Plex/Machines.py
  Cython/Plex/Scanners.pxd
  Cython/Plex/Scanners.py
  Cython/Plex/Transitions.pxd
  Cython/Plex/Transitions.py
  Cython/Shadow.py
  Cython/StringIOTree.pxd
  Cython/StringIOTree.py
Labels: cleanup

#6110 CI: Pin Numpy<2 in test dependencies.
  test-requirements-312.txt
  test-requirements.txt
Labels: Testing

#6111 [3.0.x] Fix c++ complex double_proj test
  tests/run/complex_numbers_cpp.pyx
Labels: C++, Testing

#6085 Fix bad self casts when calling methods of final types
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Symtab.py
  tests/bugs.txt
  tests/run/inherited_final_method.pyx
Labels: defect, Type Analysis

#6017 Fix issue with early inline code
  Cython/Includes/cpython/contextvars.pxd
  Cython/Includes/cpython/dict.pxd
  Cython/Includes/cpython/float.pxd
Labels: defect, Code Generation

#6104 Fix cap length
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Tests/TestTypes.py
Labels: defect, Code Generation

#6088 Improve performance hints for nogil + pxd
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  tests/compile/nogil_perf_hints.pyx
  tests/compile/nogil_perf_hints_pxd.pxd
  tests/run/nogil.pxd
  tests/run/nogil.pyx
Labels: Error Reporting

#4335 Help type checkers find Shadow typings
  Cython/Shadow.pyi
  Cython/__init__.pyi
  Cython/py.typed
  cython.py
  runtests.py
  setup.py
  tests/run/pure_py3.py
Labels: enhancement, Pure Python Mode
