Repository cython/cython, pull requests merged in 2024-10, with the labels that each got.

#6416 CI: Bump scientific-python/upload-nightly-action from 0.5.0 to 0.6.1
  .github/workflows/nightly-wheels.yml
Labels: Tools

#6422 Cast non-PyObject return values in __Pyx_TraceReturnValue invocations
  Cython/Compiler/Code.py
  tests/compile/profile_exttypereturn.pyx
Labels: defect, Code Generation

#6419 Don't override Options._default_directives
  runtests.py
Labels: Testing

#6136 Limited API fixes based on compile tests
  Cython/Utility/CConvert.pyx
  Cython/Utility/CythonFunction.c
  Cython/Utility/Dataclasses.c
  Cython/Utility/TypeConversion.c
Labels: limited api

#6092 Add a separate script that just runs code style tests
  runcodestyle.py
Labels: Tools

#6345 Use relative path for depfile
  Cython/Utils.py
  tests/build/depfile_numpy.srctree
Labels: Build System

#6432 Remove a few fstrings from 3.0.x
  Cython/Compiler/ExprNodes.py
Labels: defect

#6153 Always skip the multithreadded common_include_dir test on MacOS
  tests/build/common_include_dir.srctree
Labels: Testing

#6439 Update shebang
  Cython/Debugger/libpython.py
Labels: Tools

#6431 Move some static globals to module state
  Cython/Compiler/Code.pxd
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/Printing.c
Labels: enhancement, Code Generation

#6130 Fix refcounting of default arguments with CYTHON_AVOID_BORROWED_REFS
  Cython/Compiler/Nodes.py
Labels: defect, Code Generation

#6436 Fix ref counting of assignment expression memviews
  Cython/Compiler/ExprNodes.py
  tests/run/extra_walrus.py
Labels: defect, Code Generation
