Repository cython/cython, pull requests merged in 2024-08, with the labels that each got.

#6324 Remove GenericGetAttr utility code
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/ObjectHandling.c
Labels: cleanup

#6321 wheel CI: Update cibuildwheel to v2.20.0
  .github/workflows/wheels.yml
Labels: Build System

#6325 More robust Limited API SetItemOnTypeDict
  Cython/Utility/ExtensionTypes.c
Labels: limited api

#4585 Refactor coroutines to make use of "am_send" (new in Py3.10 and backported)
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/TypeSlots.py
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  tests/run/async_iter_pep492.pyx
  tests/run/asyncio_generators.srctree
  tests/run/builtin_next.pyx
Labels: feature, Code Generation

#6178 Avoid thread unsafe borrowed references under free-threading
  Cython/Compiler/ExprNodes.py
  Cython/Utility/CythonFunction.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/TypeConversion.c
  docs/src/userguide/source_files_and_compilation.rst
  tests/compile/buildenv.pyx
Labels: nogil CPython

#6315 pyximport: Search also pythonpath when searching for .pyx/.py file
  pyximport/pyximport.py
  tests/pyximport/pyximport_pythonpath.srctree
Labels: defect

#6144 Implement PEP-669 sys.monitoring support
  .github/workflows/ci.yml
  Cython/Compiler/Code.pxd
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/FusedNode.py
  Cython/Compiler/LineTable.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Options.py
  Cython/Compiler/ParseTreeTransforms.pxd
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/Tests/TestParseTreeTransforms.py
  Cython/Coverage.py
  Cython/Utility/Coroutine.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/Profile.c
  Tools/ci-run.sh
  docs/src/userguide/source_files_and_compilation.rst
  runtests.py
  setup.py
  tests/compile/buildenv.pyx
  tests/pypy_implementation_detail_bugs.txt
  tests/run/coverage_api.srctree
  tests/run/coverage_cmd.srctree
  tests/run/coverage_cmd_src_layout.srctree
  tests/run/coverage_cmd_src_pkg_layout.srctree
  tests/run/coverage_installed_pkg.srctree
  tests/run/coverage_nogil.srctree
  tests/run/fused_def.pyx
  tests/run/line_profile_test.srctree
  tests/run/line_trace.pyx
  tests/run/pstats_profile_test.pyx
  tests/run/pstats_profile_test_py.py
  tests/run/pstats_profile_test_pycfunc.pyx
  tests/run/sys_monitoring.py
  tests/run/trace_nogil_compilation.pyx
Labels: feature, Code Generation

#6350 PyDict_Pop() is not part of the Python 3.13 limited API
  Cython/Utility/Optimize.c
Labels: defect, Code Generation

#6349 Change C code encoding from Latin-1 to UTF-8
  Cython/Compiler/Code.py
  Cython/Compiler/Scanning.py
  Cython/Compiler/StringEncoding.py
  Cython/Coverage.py
  Cython/Utils.py
Labels: Code Generation, cleanup

#6354 Remove usages of SHA-1
  Cython/Build/Cache.py
  Cython/Build/Inline.py
  Cython/Build/IpythonMagic.py
  Cython/Compiler/Code.py
Labels: cleanup

#6346 Fixes for cdef subclasses of int/complex builtin types
  Cython/Compiler/Builtin.py
  Cython/Compiler/Nodes.py
  tests/run/cdef_subclass_builtin.pyx
Labels: defect, Code Generation

#6355 Use forward slashes in include file paths to the common include directory
  Cython/Compiler/Code.py
  tests/build/common_include_dir.srctree
  tests/windows_bugs.txt
Labels: defect, Code Generation

#5214 Turn PyxCodeWriter into a faster extension type
  Cython/Compiler/Code.pxd
  Cython/Compiler/Code.py
  Cython/Compiler/FusedNode.py
Labels: performance, enhancement, cleanup

#6351 Add utility code macro "EMPTY(bytes|tuple|...)"
  Cython/Compiler/Code.py
  Cython/Utility/Builtins.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/Dataclasses.c
  Cython/Utility/Exceptions.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/FunctionArguments.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/StringTools.c
  tests/build/common_include_dir.srctree
Labels: enhancement, Code Generation, cleanup

#6363 Fix CYTHON_LIMITED_API -> __PYX_LIMITED_VERSION_HEX
  Cython/Utility/Builtins.c
Labels: defect, Code Generation, limited api

#6362 Fix access to builtins dictionary with Py_LIMITED_API
  Cython/Utility/ObjectHandling.c
Labels: defect, Code Generation, limited api

#6369 Give cdef functions the same position and first line number as def and @cfunc functions
  Cython/Compiler/Parsing.py
  tests/compile/fused_redeclare_T3111.pyx
  tests/errors/cdefspecial.pyx
  tests/errors/cmethbasematch.pyx
  tests/errors/const_decl_errors.pyx
  tests/errors/cpdef_syntax.pyx
  tests/errors/cpdef_vars.pyx
  tests/errors/cpp_enum_redeclare.pyx
  tests/errors/cppexc_non_extern.pyx
  tests/errors/dataclass_e1.pyx
  tests/errors/dataclass_w1.pyx
  tests/errors/e_cdef_closure.pyx
  tests/errors/e_cdefemptysue.pyx
  tests/errors/e_cpp_only_features.pyx
  tests/errors/e_ctypedefornot.pyx
  tests/errors/e_exttype_freelist.pyx
  tests/errors/e_exttype_total_ordering.pyx
  tests/errors/e_func_in_pxd.pyx
  tests/errors/e_nogilcmeth.pyx
  tests/errors/e_public_cdef_private_types.pyx
  tests/errors/e_undefexttype.pyx
  tests/errors/final_methods.pyx
  tests/errors/fused_types.pyx
  tests/errors/missing_self_in_cpdef_method_T156.pyx
  tests/errors/missing_self_in_cpdef_method_T165.pyx
  tests/errors/nogil.pyx
  tests/errors/nogilcmeth.pyx
  tests/errors/pure_cclass_without_body.py
  tests/errors/pxd_cdef_class_declaration_T286.pyx
  tests/errors/pxd_signature_mismatch.pyx
  tests/errors/redeclaration_of_var_by_cfunc_T600.pyx
  tests/run/annotation_typing.pyx
  tests/run/cpp_class_redef.pyx
  tests/run/legacy_implicit_noexcept.pyx
  tests/run/nogil.pyx
Labels: Error Reporting, cleanup

#6334 [3.0.x] pyximport: Search also pythonpath when searching for .pyx/.py file
  pyximport/_pyximport3.py
  tests/pyximport/pyximport_pythonpath.srctree
Labels: defect, Build System
