Repository cython/cython, pull requests merged in 2024-04, with the labels that each got.

#6108 Make C++ conversion lengthhint limited-api friendly
  Cython/Compiler/UtilityCode.py
  Cython/Utility/CppConvert.pyx
  Cython/Utility/ObjectHandling.c
Labels: defect, Code Generation, limited api

#6115 Add tests to cover Node analyse expressions
  tests/run/analyse_expressions.srctree
Labels: Testing

#6095 [docs] Document Cython cache
  Cython/Build/Dependencies.py
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#6117 Refactor of Cache.py
  Cython/Build/Cache.py
  Cython/Build/Dependencies.py
  Cython/Compiler/Main.py
Labels: cleanup

#6131 Remove unused function from Parsing.py
  Cython/Compiler/Parsing.py
Labels: cleanup

#4673 Change CyFunction defaults to a PyObject
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Symtab.py
  Cython/Utility/CythonFunction.c
Labels: Code Generation

#6061 Add some more limited API support
  Cython/Compiler/ExprNodes.py
  Cython/Utility/CppConvert.pyx
  Cython/Utility/CythonFunction.c
  Cython/Utility/ImportExport.c
  Cython/Utility/MemoryView_C.c
  Cython/Utility/ModuleSetupCode.c
Labels: Code Generation, limited api

#5868 Always add binops to methoddef
  Cython/Compiler/Code.py
  Cython/Compiler/TypeSlots.py
  tests/run/binop_reverse_methods_GH2056.pyx
Labels: defect, Python Semantics

#4094 Fix behaviour of __class__ special variable
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ParseTreeTransforms.pxd
  Cython/Compiler/ParseTreeTransforms.py
  tests/run/pep3135_class_cell.py
  tests/run/py3k_super.py
  tests/run/py3k_super.pyx
Labels: Python Semantics

#6139 Docs: Fix example manual work in parallelization
  docs/examples/tutorial/parallelization/manual_work.pyx
Labels: Documentation

#6140 Docs: Fix string examples
  docs/examples/tutorial/string/cpp_string.pyx
  docs/examples/tutorial/string/for_bytes.pyx
  docs/examples/tutorial/string/for_char.pyx
Labels: Documentation

#6137 Update module setup code for free-threaded CPython
  Cython/Utility/ModuleSetupCode.c
  tests/compile/buildenv.pyx
Labels: enhancement, Code Generation

#6149 Use FileNotFoundError instead of OSError
  Cython/Compiler/Main.py
Labels: cleanup

#6124 Do not set exception_check if already set during analyzing pxd file
  Cython/Compiler/Nodes.py
  tests/run/legacy_implicit_noexcept_build.srctree
Labels: defect

#6155 Default-enable two build options for the nogil build
  Cython/Utility/ModuleSetupCode.c
Labels: enhancement, Code Generation

#6152 Add bindings for Py_REFCNT and use it in tests and docs
  Cython/Includes/cpython/ref.pxd
  docs/examples/userguide/language_basics/parameter_refcount.py
  docs/examples/userguide/language_basics/parameter_refcount.pyx
  tests/buffers/bufaccess.pyx
  tests/memoryview/memoryview.pyx
  tests/memoryview/memslice.pyx
  tests/run/exceptionrefcount.pyx
  tests/run/refcount_in_meth.pyx
  tests/run/test_coroutines_pep492.pyx
Labels: cleanup

#6159 Updated deque.pxd to include two functions from C++11
  Cython/Includes/libcpp/deque.pxd
  tests/run/cpp_stl_cpp11.pyx
Labels: C++, Library

#6098 Make limited API object==float work
  Cython/Utility/Optimize.c
  tests/run/isolated_limited_api_tests.srctree
Labels: Code Generation, limited api
