Repository cython/cython, pull requests merged in 2024-02, with the labels that each got.

#5957 pyximport: Use relative paths less, and correctly
  pyximport/pyximport.py
Labels: defect, Build System

#5975 Update doc requirements and pin them to recent versions (#5946)
  doc-requirements.txt
Labels: Documentation

#5968 Disable unicode test_raiseMemError
  tests/run/test_unicode.pyx
Labels: Testing

#5978 "is_extern" -> "is_external"
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
Labels: cleanup

#5905 Fix some more duplicate enum to_py utility code names
  Cython/Compiler/PyrexTypes.py
  tests/run/cpdef_enums_import.srctree
Labels: defect, Code Generation

#5941 "failed to import" warning once per cpdef enum
  Cython/Utility/CpdefEnums.pyx
Labels: Error Reporting

#5920 Modified "pretend_to_initialize" for c++
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ModuleSetupCode.c
Labels: C++

#5987 Warn about discarting const qualifier
  Cython/Compiler/Nodes.py
  tests/errors/const_decl_errors.pyx
Labels: Error Reporting

#5988 Fix memoryview type checking issue
  Cython/Compiler/PyrexTypes.py
  tests/run/builtin_memory_view.pyx
Labels: defect, Code Generation

#5963 Explicitly set exception cause in __Pyx_Generator_Replace_StopIteration
  Cython/Utility/Coroutine.c
  tests/run/generators_pep479.pyx
Labels: Python Semantics

#5985 add tag for numpy in error test, update actions versions
  .github/workflows/ci.yml
  .github/workflows/wheels.yml
  tests/errors/nogil_buffer_acquisition.pyx
Labels: Testing

#5996 Skip builtin memoryview test on Python 2 (3.0.x)
  tests/run/builtin_memory_view.pyx
Labels: Testing

#5993 Force closing gzip file in TestCyCache (#5945)
  Cython/Build/Tests/TestCyCache.py
Labels: Testing

#5992 add tag for numpy in error test, update actions versions (#5985)
  .github/workflows/ci.yml
  .github/workflows/wheels.yml
  tests/errors/nogil_buffer_acquisition.pyx
Labels: Testing

#5994 Reimplement "Dependencies.strip_string_literals()"
  Cython/Build/Dependencies.py
  Cython/Build/Tests/TestStripLiterals.py
Labels: defect, Build System

#4698 Handle platforms where sizeof(funcptr) != sizeof(void*)
  Cython/Utility/ImportExport.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/TypeConversion.c
  tests/run/cimport.srctree
Labels: defect, Code Generation

#4897 Parse structural pattern matching
  Cython/Compiler/MatchCaseNodes.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.pxd
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.pxd
  Cython/Compiler/Parsing.py
  Cython/TestUtils.py
  Tools/ci-run.sh
  tests/errors/e_patma_extra.pyx
  tests/run/extra_patma.pyx
  tests/run/test_patma.py
Labels: feature, Parsing, Python Semantics

#5912 Use literal exception values instead of strings where possible.
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  Cython/Compiler/PyrexTypes.py
Labels: enhancement, Type Analysis

#6003 Use Python 3.13a4 PyCFunctionFastWithKeywords
  Cython/Utility/CythonFunction.c
  Cython/Utility/ModuleSetupCode.c
Labels: enhancement, Code Generation

#5999 Warn when function returning python object is marked as noexcept
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.py
  tests/errors/w_noexcept.pyx
  tests/run/legacy_implicit_noexcept.pyx
Labels: Error Reporting

#6005 Fix call of final fused cdef functions
  Cython/Compiler/PyrexTypes.py
  tests/run/fused_cdef.pyx
Labels: defect, Code Generation

#6008 [3.0.X] Fix call of final fused cdef functions (#6005)
  Cython/Compiler/PyrexTypes.py
  tests/run/fused_cdef.pyx
Labels: defect, Code Generation

#6007 [3.0.x] Warn when function returning python object is marked as noexcept (#5999)
  Cython/Compiler/Nodes.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Parsing.py
  tests/errors/w_noexcept.pyx
  tests/run/legacy_implicit_noexcept.pyx
Labels: Error Reporting

#5956 Tolerate and escape globbing characters in sys.path
  Cython/Utils.py
  tests/run/sys_path_globbed.srctree
Labels: defect, Build System

#6010 Fix typo in assertion (3.0.x)
  pyximport/_pyximport2.py
  pyximport/_pyximport3.py
Labels: cleanup

#6006 Move Py_UNICODE out of universal utility code
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/StringTools.c
  Cython/Utility/TypeConversion.c
Labels: cleanup

#6025 Move Py_UNICODE out of universal utility code (#6006) (3.0.x backport)
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Utility/StringTools.c
  Cython/Utility/TypeConversion.c
Labels: Code Generation, cleanup

#6016 Fix a typo in vectorcall code
  Cython/Utility/ObjectHandling.c
Labels: defect, Code Generation

#6024 Fix PyImport_AddModuleRef on the limited API
  Cython/Utility/ModuleSetupCode.c
Labels: defect, limited api

#6035 Fix (most) unused variable warnings about clineno
  Cython/Compiler/ModuleNode.py
Labels: defect, Code Generation

#6028 Initialize code objects with loop over table
  Cython/Compiler/Code.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Naming.py
  Cython/Utility/ModuleSetupCode.c
Labels: enhancement, Code Generation

#5972 Don't miss a required PyObject_GC_Track() in dealloc
  Cython/Compiler/ModuleNode.py
  tests/run/exttype_gc.pyx
Labels: defect, Code Generation

#6037 Added missing `replace` functions to C++ `std::string` definition
  Cython/Includes/libcpp/string.pxd
  tests/run/cpp_stl_string.pyx
Labels: C++, enhancement, Library

#6041 Add fixing of warning in 3.0.9 to CHANGES.rst
  CHANGES.rst
Labels: Documentation
