Repository cython/cython, pull requests merged in 2025-03, with the labels that each got.

#6699 Define buffer typeinfo structs as const
  Cython/Compiler/Buffer.py
  Cython/Utility/Buffer.c
  Cython/Utility/MemoryView.pyx
  Cython/Utility/MemoryView_C.c
Labels: cleanup

#6684 Reduce overhead when validating keyword arguments
  Cython/Compiler/Naming.py
  Cython/Compiler/Nodes.py
  Cython/Utility/FunctionArguments.c
Labels: enhancement, Code Generation

#6697 Implement a 'timeit' variant as "cythonize --timeit"
  Cython/Build/Cythonize.py
  Cython/Build/Inline.py
  Cython/Build/Tests/TestInline.py
  tests/build/cythonize_cymeit.srctree
Labels: feature, Build System

#6705 Fix incorrect code generation for method override
  Cython/Compiler/Symtab.py
  tests/run/static_method_inheritance.pyx
Labels: defect, Type Analysis

#6703 Some profiling/monitoring code object changes
  Cython/Compiler/Code.py
  Cython/Compiler/Nodes.py
  Cython/Utility/Profile.c
Labels: defect, Code Generation, Memory Leak

#6708 Add a missing "const" in memoryview code
  Cython/Utility/MemoryView.pyx
Labels: cleanup

#6602 Avoid exception normalisation of unused exception instances during "except" handling
  Cython/Compiler/Nodes.py
Labels: Optimization, Code Generation

#6709 Disable monitoring in parallel/prange
  Cython/Compiler/Nodes.py
  Cython/Utility/Profile.c
Labels: freethreading CPython

#6669 Make CachedCFunction mechanism thread-safe
  Cython/Utility/MemoryView_C.c
  Cython/Utility/ObjectHandling.c
Labels: freethreading CPython

#6689 Fix limited API slice and uchar
  Cython/Compiler/Builtin.py
  Cython/Compiler/Optimize.py
  Cython/Includes/cpython/bool.pxd
  Cython/Utility/Builtins.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/StringTools.c
  tests/limited_api_bugs.txt
  tests/memoryview_tests.txt
  tests/run/builtinslice.pyx
  tests/run/cpp_stl_conversion.pyx
  tests/run/fused_types.pyx
  tests/run/py_ucs4_type.pyx
Labels: limited api

#6637 Revert "Handle platforms where sizeof(funcptr) != sizeof(void*) (#4698)"
  Cython/Utility/ImportExport.c
  Cython/Utility/TypeConversion.c
  tests/run/cimport.srctree
Labels: Code Generation, cleanup

#6606 Improve critical sections in CyFunction
  Cython/Utility/CythonFunction.c
Labels: defect, Code Generation, cleanup

#6713 Avoid clang uninitialized member warn in unbound methods
  Cython/Utility/ObjectHandling.c
Labels: enhancement, Code Generation

#6719 Remove old Limited API exception handling code
  Cython/Utility/Exceptions.c
Labels: defect, cleanup, limited api

#6721 Fix reference counting issue in code object cache
  Cython/Utility/ModuleSetupCode.c
Labels: defect, freethreading CPython

#6733 Add benchmark runner to compare different Cython revisions
  .github/workflows/ci.yml
  Cython/Build/Cythonize.py
  Demos/benchmarks/bm_async_generators.py
  Demos/benchmarks/bm_chaos.pxd
  Demos/benchmarks/bm_chaos.py
  Demos/benchmarks/bm_fib.py
  Demos/benchmarks/bm_generators.py
  Demos/benchmarks/run_benchmarks.py
Labels: performance, Tools

#6707 Hints/guidance for thread-safety
  docs/src/userguide/freethreading.rst
Labels: Documentation, freethreading CPython

#6732 Optimise async implementation
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
Labels: performance, defect

#6636 Silence GCC -Wpedantic in C function pointer casts
  Cython/Compiler/Code.py
  Cython/Compiler/Nodes.py
  Cython/Utility/CythonFunction.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
Labels: Code Generation, cleanup

#6736 Inline the vectorcall function lookup to avoid the C-API call
  Cython/Utility/ObjectHandling.c
Labels: performance, enhancement

#6738 Avoid a performance panelty in CPython 3.12/13 when creating a StopIteration
  Cython/Utility/Coroutine.c
Labels: performance, defect

#6735 Avoid raising StopIteration from iternext
  Cython/Utility/AsyncGen.c
  Cython/Utility/Coroutine.c
Labels: performance, enhancement, Code Generation

#6690 Enable multi-phase init for Limited API by default
  Cython/Utility/ModuleSetupCode.c
  setup.py
  tests/limited_api_bugs.txt
Labels: limited api

#6717 Optimise divmod() for all C integer types
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/TreePath.py
  Cython/Utility/Builtins.c
  Cython/Utility/CMath.c
  tests/limited_api_bugs.txt
  tests/run/builtin_divmod.py
  tests/run/tuple_constants.pyx
Labels: Optimization, Code Generation, Type Analysis

#6742 let vectorcall use space allocated for self
  Cython/Utility/ObjectHandling.c
Labels: performance, limited api

#6744 Use vectorcall when calling known builtin/ext types
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Optimize.py
  tests/errors/tree_assert.pyx
  tests/run/all.pyx
  tests/run/any.pyx
  tests/run/builtin_sorted.pyx
  tests/run/isinstance.pyx
Labels: performance, enhancement, Code Generation

#6743 Deprecate "numpy.math"
  Cython/Includes/numpy/math.pxd
Labels: cleanup

#6758 replace quansight-labs/setup-python with actions/setup-python
  .github/workflows/ci.yml
Labels: Testing

#6747 Speed up method calls with PyObject_VectorcallMethod
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Naming.py
  Cython/Utility/ObjectHandling.c
  tests/run/call_py_cy.pyx
  tests/run/genexpr_arg_order.py
Labels: performance, Optimization, Code Generation

#6761 Restore some C-API calls that were removed in Py3.13a1 but came back afterwards
  Cython/Utility/Builtins.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/StringTools.c
Labels: enhancement, Code Generation

#6772 Remove unused coroutine code
  Cython/Utility/Coroutine.c
Labels: cleanup
