Repository cython/cython, pull requests merged in 2025-08, with the labels that each got.

#7059 Fix omission in unicode character generation
  Cython/Compiler/Lexicon.py
  Tools/cython-generate-lexicon.py
Labels: defect, Python Semantics

#7065 Change a COMPILING_IN_PYPY to AVOID_BORROWED_REFS
  Cython/Utility/Optimize.c
Labels: Code Generation

#7074 Improve GraalPy support
  Cython/Includes/cpython/array.pxd
  Cython/Includes/cpython/datetime.pxd
  Cython/Utility/Builtins.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/Exceptions.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/arrayarray.h
  runtests.py
Labels: Code Generation

#7079 Revert "CI: Fix Windows build in Py3.13 by forcing the upgrade to Py3…
  .github/workflows/ci.yml
Labels: Testing

#6989 Fix code-generation with walrus+literals
  Cython/Compiler/ExprNodes.py
  tests/run/extra_walrus.py
Labels: defect, Code Generation

#7092 Remove uses of HAVE_LONG_LONG
  Cython/Utility/Buffer.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/Optimize.c
  Cython/Utility/Overflow.c
  Cython/Utility/TypeConversion.c
Labels: Code Generation, cleanup

#7077 Remove dataclasses fallback code
  Cython/Compiler/Dataclass.py
  Cython/Utility/Dataclasses.c
  Cython/Utility/Dataclasses.py
Labels: cleanup

#7097 Extract common code from the fused functions dispatch into utility functions
  Cython/Compiler/FusedNode.py
  Cython/Utility/FusedFunction.pyx
Labels: cleanup

#7096 Fix empty container test
  Cython/Compiler/ExprNodes.py
Labels: defect, Code Generation

#7099 HTML annotation UI: toggle +/- symbols for expand/collapse state
  Cython/Compiler/Annotate.py
Labels: enhancement, Tools

#7091 Avoid and test some undefined behaviour in integer shifts
  Cython/Utility/Optimize.c
  tests/run/pyintop.pyx
Labels: defect, Code Generation

#7104 Remove a breakpoint() call that shouldn't be there
  Cython/CodeWriter.py
Labels: cleanup

#7105 Enable one more fstring error test
  tests/run/test_fstring.pyx
Labels: Testing

#7063 Fix a crash in sys.monitoring
  Cython/Utility/Profile.c
  tests/run/sys_monitoring.py
Labels: defect, Code Generation

#7115 Improve "unique reference" checking
  Cython/Compiler/ExprNodes.py
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
  Cython/Utility/StringTools.c
  tests/run/freethreaded_list_indexing.pyx
Labels: freethreading CPython

#7118 Add an option to immortalize cached constants
  Cython/Compiler/Code.py
  Cython/Utility/ModuleSetupCode.c
  docs/src/userguide/source_files_and_compilation.rst
Labels: freethreading CPython

#3263 Disable parallel cythonization for "spawn" start method.
  Cython/Build/Dependencies.py
Labels: defect, Build System

#7120 Replace list with array in import code
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Parsing.py
  Cython/Utility/ImportExport.c
  tests/errors/nogil.pyx
Labels: enhancement, Code Generation

#7123 Remove unused code and conditionals that applied only to Py<3.8
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/TypeSlots.py
  Cython/Utility/Builtins.c
  Cython/Utility/CythonFunction.c
  Cython/Utility/Embed.c
  Cython/Utility/ExtensionTypes.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
Labels: cleanup

#7082 Update C/C++ py_safe locking loops...
  Cython/Includes/libc/threads.pxd
  Cython/Includes/libcpp/mutex.pxd
  docs/src/userguide/freethreading.rst
Labels: C++, Library, freethreading CPython
