Repository cython/cython, pull requests merged in 2025-02, with the labels that each got.

#6585 Add type-inference to prange target
  Cython/Compiler/FlowControl.py
  tests/run/sequential_parallel.pyx
Labels: Type Analysis, Cython Language Feature

#6639 Fix GetSet function definition for coroutine ci_running
  Cython/Utility/Coroutine.c
  tests/run/async_def.pyx
Labels: defect, Code Generation

#6638 Improve code-gen for critical_section error path
  Cython/Compiler/Nodes.py
Labels: Code Generation, freethreading CPython

#6643 Enable a few more Limited API tests
  tests/limited_api_bugs.txt
  tests/limited_api_bugs_38.txt
  tests/run/importfrom.pyx
Labels: Testing, limited api

#6649 Enable Limited API in srctree tests
  runtests.py
  tests/limited_api_bugs.txt
  tests/memoryview_tests.txt
  tests/run/abitests.srctree
  tests/run/freethreading_compatible.srctree
  tests/run/isolated_limited_api_tests.srctree
  tests/run/reimport_from_subinterpreter.srctree
  tests/run/subinterpreters.srctree
  tests/run/subinterpreters_threading_stress_test.srctree
Labels: Testing, limited api

#6370 Fix test setup for "cpp_locals"
  Cython/Compiler/ParseTreeTransforms.py
  runtests.py
  tests/run/cpp_method_overloading.pyx
  tests/run/cpp_mutex.pyx
  tests/run/cpp_stl_algo_sample.pyx
  tests/run/cpp_stl_any.pyx
  tests/run/cpp_stl_optional.pyx
  tests/run/cpp_stl_random.pyx
  tests/run/cpp_stl_span.pyx
  tests/run/cpp_stl_string.pyx
Labels: defect, Testing

#6659 Stop Cython compiling itself in freethreaded builds
  setup.py
Labels: freethreading CPython

#6647 Fix implementation and usage of PyDict_GetItemRef
  Cython/Utility/ImportExport.c
  Cython/Utility/ModuleSetupCode.c
  Cython/Utility/ObjectHandling.c
Labels: limited api

#6670 Better fix for common_include_dir
  tests/build/common_include_dir.srctree
Labels: Testing

#5871 Allow cimport of cpython in the limited API
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Options.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Includes/cpython/array.pxd
  Cython/Includes/cpython/complex.pxd
  Cython/Includes/cpython/contextvars.pxd
  Cython/Includes/cpython/datetime.pxd
  Cython/Includes/cpython/longintrepr.pxd
  Cython/Shadow.py
  tests/run/isolated_limited_api_tests.srctree
Labels: limited api

#6674 Fix subinterpreters test in 3.14
  tests/run/subinterpreters.srctree
Labels: Testing

#6680 Fix outdated URL for packaging tutorial
  docs/src/quickstart/build.rst
Labels: Documentation

#3694 Limited api work
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ImportExport.c
Labels: limited api

#6665 Make traceback frame cache thread safe
  Cython/Utility/MemoryView_C.c
  Cython/Utility/ModuleSetupCode.c
  tests/run/threading_stress_tests.pyx
Labels: defect, freethreading CPython

#6687 Enable one more Limited API test
  tests/limited_api_bugs.txt
Labels: Testing, limited api

#6681 remove static_link from GDB API dependencies
  Cython/Debugger/libcython.py
Labels: Tools
