Repository cython/cython, pull requests merged in 2025-04, with the labels that each got.

#6771 Use optimized GetAwaitableIter function
  Cython/Utility/Coroutine.c
Labels: defect, Code Generation

#6728 Generate and use shared library for MemoryView Utility code [Context attribute]
  Cython/Build/Dependencies.py
  Cython/Build/SharedModule.py
  Cython/Compiler/CmdLine.py
  Cython/Compiler/Code.pxd
  Cython/Compiler/Code.py
  Cython/Compiler/CythonScope.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/Main.py
  Cython/Compiler/MemoryView.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Options.py
  Cython/Compiler/ParseTreeTransforms.py
  Cython/Compiler/Pipeline.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Compiler/Tests/TestCmdLine.py
  Cython/Compiler/UtilityCode.py
  Cython/Compiler/Visitor.py
  Cython/Distutils/build_ext.py
  Cython/Tests/TestShadow.py
  Cython/Utility/MemoryView.pxd
  docs/src/userguide/faq.rst
  docs/src/userguide/source_files_and_compilation.rst
  tests/limited_api_bugs.txt
  tests/memoryview/memoryview_no_shared_utility.srctree
  tests/memoryview/memoryview_shared_utility.srctree
Labels: feature, Code Generation

#6679 Fix logic for c_safe_identifier to extension types
  Cython/Compiler/Symtab.py
  tests/run/cclass_attr.pyx
Labels: defect, Code Generation

#6749 Update definition of critical_section in Shadow
  Cython/Shadow.py
Labels: Pure Python Mode

#6777 Fix a possible race when setting up the common types
  Cython/Utility/CommonStructures.c
Labels: freethreading CPython

#6513 Allow the user to declare subinterpreter support
  Cython/Compiler/Code.py
  Cython/Compiler/ModuleNode.py
  Cython/Compiler/Options.py
  Cython/Compiler/Symtab.py
  docs/src/userguide/source_files_and_compilation.rst
  tests/errors/w_subinterpreters.pyx
  tests/run/subinterpreters.srctree
  tests/run/subinterpreters_threading_stress_test.srctree
Labels: feature, Code Generation

#6780 Have the benchmark runner report compiled file sizes
  .github/workflows/ci.yml
  Demos/benchmarks/run_benchmarks.py
Labels: Tools

#6782 Fix __Pyx_Owned_Py_None
  Cython/Utility/TypeConversion.c
Labels: defect, Code Generation

#6776 Fix utility code passing context to requirements
  Cython/Compiler/Code.py
Labels: cleanup

#6788 Enable no-copy optimization on Limited API
  Cython/Compiler/ExprNodes.py
Labels: limited api

#6625 Add wrappings for C++20 thread synchronization functions
  Cython/Includes/libcpp/barrier.pxd
  Cython/Includes/libcpp/latch.pxd
  Cython/Includes/libcpp/semaphore.pxd
  tests/macos_cpp_bugs.txt
  tests/run/libcpp_threadsync_cpp20.pyx
Labels: C++, Library

#6796 Fix documentation to mention get_ipython_cache_dir() instead of IPYTHONDIR for %%cython cell cache location
  Cython/Build/IpythonMagic.py
Labels: Documentation

#6764 Add embedsignature for special methods
  Cython/Compiler/AutoDocTransforms.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Symtab.py
  tests/limited_api_bugs.txt
  tests/run/cpp_stl_conversion.pyx
  tests/run/embedsignatures.pyx
  tests/run/embedsignatures_clinic.pyx
  tests/run/embedsignatures_python.pyx
  tests/run/skip_limited_api_helper.pxi
Labels: enhancement, Cython Language Feature

#6802 Fix UnboundLocalError with non-ascii names
  Cython/Compiler/Code.py
Labels: defect, Code Generation

#6803 Fix formatting of a link in the docs
  docs/src/userguide/source_files_and_compilation.rst
Labels: Documentation

#6801 Reimplement the divmod() C integer optimisation using dynamic code generation
  Cython/Compiler/Builtin.py
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  Cython/Compiler/Symtab.py
  Cython/Utility/Builtins.c
  tests/run/builtin_divmod.py
  tests/run/builtin_divmod_pyx.pyx
Labels: defect, Optimization, Code Generation

#6789 Simplify __Pyx_PyType_Ready for single inheritance case
  Cython/Utility/ExtensionTypes.c
Labels: enhancement, Code Generation, freethreading CPython

#6773 Fix a couple of issues with __Pyx_Coroutine_get_frame
  Cython/Utility/Coroutine.c
Labels: defect, Code Generation, freethreading CPython

#6382 Namespace-only named cpdef enums
  Cython/Compiler/Nodes.py
  Cython/Utility/CpdefEnums.pyx
  docs/src/userguide/language_basics.rst
  tests/run/cpdef_enums.pyx
  tests/run/cpp_stl_conversion.pyx
Labels: defect, Cython Language Feature

#5799 Take CO_* from inspect in limited API
  Cython/Compiler/ModuleNode.py
  Cython/Utility/ModuleSetupCode.c
Labels: limited api

#6814 Small correction to changelog
  CHANGES.rst
Labels: Documentation

#6817 fix typo in free-threading guide
  docs/src/userguide/freethreading.rst
Labels: Documentation

#6819 docs: Use pip for readthedocs build to fix setuptools failure.
  .readthedocs.yaml
Labels: Documentation

#6813 Fix issue with unicode cpdef args
  Cython/Compiler/PyrexTypes.py
  tests/run/unicode_identifiers.pxd
  tests/run/unicode_identifiers.pyx
Labels: defect, Code Generation
