Repository cython/cython, pull requests merged in 2025-09, with the labels that each got.

#7125 Fix a small typo
  Cython/Compiler/Symtab.py
Labels: cleanup

#7112 Discard all line endings from source lines for error reporting and C source comments
  Cython/Compiler/Code.py
  Cython/Compiler/Errors.py
  Cython/Compiler/Nodes.py
  Cython/Compiler/Scanning.py
Labels: Error Reporting, cleanup

#7132 Feature/fix tutorial setup py
  docs/src/tutorial/cython_tutorial.rst
Labels: Documentation

#7136 Add missing ufunc decorator to type annotations
  Cython/Shadow.pyi
Labels: Pure Python Mode

#7140 Update comment in __Pyx__PyCode_New
  Cython/Utility/ModuleSetupCode.c
Labels: cleanup

#7148 Correct the Limited API documentation supported versions
  docs/src/userguide/limited_api.rst
Labels: Documentation

#7154 docs: Automatically adapt year in copyright line
  docs/conf.py
Labels: Documentation

#7160 Use a fast and safe conversion from PyLong to C long.
  Cython/Utility/Optimize.c
  Cython/Utility/TypeConversion.c
Labels: defect, Code Generation

#7163 Remove unused scope class
  Cython/Compiler/Symtab.py
Labels: cleanup

#7167 Remove some spurious debugging code
  Cython/Compiler/Scanning.py
Labels: cleanup

#7168 Add code style check to spot calls to breakpoint()
  runtests.py
  setup.cfg
Labels: Testing

#7170 Optimise integer formatting for typedefs.
  Cython/Compiler/ExprNodes.py
  Cython/Compiler/PyrexTypes.py
  tests/run/fstring.pyx
Labels: enhancement, Optimization, Code Generation
